First commit
UTN-FRBA-Mobile/Play2Play pull request #1
Opened 2021-05-09 16:00 UTC by dylanmuszelml

## Descripción

Se agrega el proyecto base.

2021-05-09 23:27 UTC, florencialipchak commented on gradlew.bat
> +echo ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
¿Este archivo debería subirse?

2021-05-09 23:27 UTC, florencialipchak commented on gradlew
> +        (8) set -- "$args0" "$args1" "$args2" "$args3" "$args4" "$args5" "$args6" "$args7" ;;
qué es esto ah

2021-05-10 00:14 UTC, DylanMuszel commented on gradlew.bat
> +echo ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
Sip

2021-05-10 00:15 UTC, DylanMuszel commented on gradlew
> +        (8) set -- "$args0" "$args1" "$args2" "$args3" "$args4" "$args5" "$args6" "$args7" ;;
Son archivos base que se crean cuando se crea el proyecto, no lo agregué yo jajaj

2021-05-10 01:49 UTC, florencialipchak requested changes

2021-05-10 01:49 UTC, florencialipchak commented on .gitignore
> +*.DS_STORE
¿Agregás porfa la carpeta .idea? Porque nos va a romper todo si no.

2021-05-10 01:54 UTC, dylanmuszelml commented on .gitignore
> +*.DS_STORE
Buena idea, pensé que ya estaba todo lo necesario, ahí lo sumo y chequeo si hace falta algo más

2021-05-10 02:20 UTC, dylanmuszelml commented on .gitignore
> +*.DS_STORE
Bueno, se lo saqué por las dudas jajaj

2021-05-10 02:22 UTC, florencialipchak approved these changes

2021-05-10 13:12 UTC, emanuelandrada commented on .gitignore
> +*.DS_STORE
La carpeta `.idea` es molestísima.

2021-05-13 21:42 UTC, PadillaJuan approved these changes

2021-05-13 22:36 UTC, merged