Conexión Bluetooth
UTN-FRBA-Mobile/Play2Play pull request #10
Opened 2021-05-25 23:34 UTC by florlipchak

- Se agregan las implementaciones de un BluetoothClient y un BluetoothServer, ambos son hilos que dentro escuchan los sockets.  Se crean por un BluetoothConnectionCreator.
- Cualquier mensaje que le llegue al Server será broadcasteado a todos los demás Clients.
- Se agrega la interfaz Message que será implementada por todos los mensajes que se quieran enviar entre dispositivos. Por ahora el único creado es el Handshake, que le comunica al Server el nombre de la persona que se unió. La lógica del handhsake quedará en otro PR.
- Se separa la lógica de creación de la TuttiFruttiActivity según se trate del Server o de un Client.
- Los logs se hacen desde Logger, que solo los muestra cuando se está en Debug.

2021-05-27 23:30 UTC, vaalecav approved these changes
Hermoso laburo chiques ❤️

2021-05-27 23:30 UTC, vaalecav commented on app/src/main/java/com/p2p/framework/bluetooth/BluetoothClient.kt
> +            Log.e(TAG, "Could not close the client socket", e)
```suggestion
            Logger.e(TAG, "Could not close the client socket", e)
```

2021-05-27 23:30 UTC, vaalecav commented on app/src/main/java/com/p2p/framework/bluetooth/BluetoothConnectionCreatorImp.kt
> +                true
Agreguemos un TODO de lo que vamos a hacer con el mensaje 🤗

2021-05-27 23:30 UTC, vaalecav commented on app/src/main/java/com/p2p/framework/bluetooth/BluetoothConnectionThread.kt
> +            Logger.d(TAG, "Writting...")
```suggestion
            Logger.d(TAG, "Writing...")
```

2021-05-27 23:30 UTC, vaalecav commented on app/src/main/java/com/p2p/framework/bluetooth/BluetoothConnectionThread.kt
> +            Log.e(TAG, "Error occurred when sending data", e)
```suggestion
            Logger.e(TAG, "Error occurred when sending data", e)
```

2021-05-27 23:30 UTC, vaalecav commented on app/src/main/java/com/p2p/presentation/base/GameConnectionType.kt
> +    const val EXTRA = "GAME_CONNECTION_TYPE_EXTRA"
Que sería extra?

2021-05-27 23:39 UTC, brendaboryszanski approved these changes
tremendo :)

2021-05-27 23:39 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/utils/Logger.kt
> +    fun v(tag: String, msg: String, tr: Throwable? = null) {
Iba a decir q me molesta los nombres cortos, pero el propio Log de android le pone eso... asi q :(

2021-05-27 23:50 UTC, dylanmuszelml requested changes

2021-05-27 23:56 UTC, florlipchak commented on app/src/main/java/com/p2p/presentation/base/GameConnectionType.kt
> +    const val EXTRA = "GAME_CONNECTION_TYPE_EXTRA"
Es el nombre con el que se va a guardar esa variable "GAME_CONNECTION_TYPE_SERVER" o "GAME_CONNECTION_TYPE_CLIENT". Es como un clave -> valor y el extra vendría a ser la clave para pedirlo después.

2021-05-27 23:57 UTC, florlipchak commented on app/src/main/java/com/p2p/framework/bluetooth/BluetoothConnectionCreatorImp.kt
> +                true
Dale, banco.

2021-05-28 00:12 UTC, PadillaJuan approved these changes

2021-05-28 03:03 UTC, merged