Creación de las conexiones
UTN-FRBA-Mobile/Play2Play pull request #11
Opened 2021-05-26 03:59 UTC by florlipchak

La lógica de creación de conexiones queda delegada en el GamesViewModel que cada juego debe implementar.

2021-05-26 15:57 UTC, dylanmuszelml requested changes

2021-05-26 15:57 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/base/game/GameViewModel.kt
> +            GameConnectionType.SERVER -> bluetoothConnectionCreator.createServer()
Se debería guardar en alguna variable el server y el client.

2021-05-26 15:57 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/base/game/GameViewModel.kt
> +        const val UNKNOWN = "Desconocido"
Esto debería estar en el strings.xml

2021-05-26 15:57 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/base/game/GameViewModel.kt
> +    fun onCreateOrJoin() {
```suggestion
    fun createOrJoin() {
```

2021-05-26 15:57 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/base/BaseMVVMActivity.kt
> +abstract class BaseMVVMActivity<E : Any, VM : BaseViewModel<E>> : BaseActivity() {
Me quedé pensando en esto, capaz podría ser un `BaseGameActivity` directamente y que el `E` sea `E: GameEvent`?

2021-05-26 15:57 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/base/game/gameCreationEvents.kt
> +sealed class GameCreationEvent
Esto no es un evento de la creación, es un evento general del juego, o no? No sería `GameEvent`?

2021-05-26 15:57 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/base/game/gameCreationEvents.kt
> +open class SpecificCreationEvents : GameCreationEvent()
Lo mismo, no sería `SpecificGameEvent`?

2021-05-26 15:57 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiViewModel.kt
> +    fun onStart() {
No sería mejor directo en el `init`? Es raro que se lo llame desde un evento del ciclo de vida.

2021-05-26 15:57 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/base/game/GameViewModel.kt
> +            GameConnectionType.SERVER -> dispatchSingleTimeEvent(GoToServerLobby)
Si es el server acá tiene que ir al create, no al lobby.

2021-05-26 15:57 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiViewModelFactory.kt
> +            ConnectionType(gameConnectionType, device),
Me gusta cómo resolviste esto

2021-05-26 15:57 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/tuttiFruttiCreationEvents.kt
> +object GoToSelectCategories : SpecificCreationEvents()
Lo que decía, no termino de entender este event

2021-05-26 16:14 UTC, florlipchak commented on app/src/main/java/com/p2p/presentation/base/game/GameViewModel.kt
> +            GameConnectionType.SERVER -> bluetoothConnectionCreator.createServer()
Cierto, lo meto en una variable.

2021-05-26 16:14 UTC, florlipchak commented on app/src/main/java/com/p2p/presentation/base/game/GameViewModel.kt
> +        const val UNKNOWN = "Desconocido"
aah, no sabía que estas cosas también iban ahí.

2021-05-26 16:16 UTC, florlipchak commented on app/src/main/java/com/p2p/presentation/base/game/gameCreationEvents.kt
> +sealed class GameCreationEvent
o sea ya existe GameEvent, que es de la pantalla de seleciconar y crear el juego, pero yo no quiero que sea uno de esos eventos. Podríamos decir que son eventos para crear el entorno de juego si no, porque es cierto que el del lado del client no crea nada.

2021-05-26 16:17 UTC, florlipchak commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiViewModel.kt
> +    fun onStart() {
banco

2021-05-26 16:18 UTC, florlipchak commented on app/src/main/java/com/p2p/presentation/base/game/GameViewModel.kt
> +            GameConnectionType.SERVER -> dispatchSingleTimeEvent(GoToServerLobby)
no, cómo. La idea es que llegue acá una vez que toca el último botón de crear juego, y esto lo mande al lobby donde se va a llamar al crear server.

2021-05-26 16:18 UTC, florlipchak commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiViewModel.kt
> +        }
Es que no, cuando arranca la activity si es un server quiero ir a la pantalla de Seleccionar categorías, pero si es un client quiero ir directo al lobby, no hay nada para hacer. Esta parte del flujo es el primer botón de "crear o unirse"

2021-05-26 16:19 UTC, florlipchak commented on app/src/main/java/com/p2p/presentation/tuttifrutti/tuttiFruttiCreationEvents.kt
> +object GoToSelectCategories : SpecificCreationEvents()
lo expliqué arriba.

2021-05-26 16:30 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/base/BaseMVVMActivity.kt
> +abstract class BaseMVVMActivity<E : Any, VM : BaseViewModel<E>> : BaseActivity() {
Tenés razónn, dije cualquiera jajaja, perdón

2021-05-26 16:30 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/base/game/gameCreationEvents.kt
> +sealed class GameCreationEvent
Eso es GamesEvent, esto sería GameEvent en minúscula jajaj. Pero eso, no tiene que ver con la creación en sí, uno de los eventos va a ser GoToCreate, pero nada más. `BaseGameEvent` si no?

2021-05-26 16:31 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/base/game/GameViewModel.kt
> +            GameConnectionType.SERVER -> dispatchSingleTimeEvent(GoToServerLobby)
Claro, pero esto no se llama cuando se toca el botón de crear, esto se debería llamar cuando se inicia la activity.

2021-05-26 16:31 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiViewModel.kt
> +        }
Claro, pero para mí eso es crearounirse.

2021-05-28 00:02 UTC, DylanMuszel requested changes

2021-05-28 00:05 UTC, florlipchak commented on app/src/main/java/com/p2p/presentation/base/game/GameViewModel.kt
> +    lateinit var connection: BluetoothConnection
dale, banco. Yo creo que no existiría pero de última hacemos eso después.

2021-05-28 00:08 UTC, florlipchak commented on app/src/main/java/com/p2p/presentation/base/game/GameViewModel.kt
> +                    "A bluetooth device should be passed on the activity creation"
el tema es que solo lo queremos validar si es un client, para el server no sería. Decís que al activity le corresponde saber eso?

2021-05-28 00:08 UTC, florlipchak commented on app/src/main/java/com/p2p/presentation/base/game/GameViewModel.kt
> +                    client.onConnected { // TODO: should wait until connected to continue any processing
uh, sí, eso quedó.

2021-05-28 00:12 UTC, florlipchak commented on app/src/main/java/com/p2p/presentation/base/game/GameViewModel.kt
> +                        it.write(HandshakeMessage(userSession.getUserName() ?: R.string.unknown.toString()))
me tenés harta. Me gustaba en el companion object ah.
(dale, sí, lo meto ahí)

2021-05-28 00:13 UTC, florlipchak commented on app/src/main/java/com/p2p/presentation/base/game/GameViewModel.kt
> +    protected abstract fun creationEvent(): GameEvent
sip, no sé por qué no me convencía del todo porque no lo siento como un atributo de la clase, pero lo pongo así si querés.

2021-05-28 00:13 UTC, florlipchak commented on app/src/main/java/com/p2p/presentation/base/game/gameEvents.kt
> +open class SpecificGameEvents : GameEvent()
jejo

2021-05-28 00:14 UTC, florlipchak commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiActivity.kt
> +        viewModel.createOrJoin()
lo meto en el oncreate para que quede bien explícito que se arranca ahí.

2021-05-28 00:21 UTC, florlipchak commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiActivity.kt
> +        viewModel.createOrJoin()
bah, no, mentira. Lo voy a dejar en el init del viewModel

2021-05-28 00:29 UTC, DylanMuszel commented on app/src/main/java/com/p2p/presentation/base/game/GameViewModel.kt
> +                    "A bluetooth device should be passed on the activity creation"
Aaaaah, no claro! Tenés razón, está perfecto.

2021-05-28 00:31 UTC, DylanMuszel commented on app/src/main/java/com/p2p/presentation/base/game/GameViewModel.kt
> +    protected abstract fun creationEvent(): GameEvent
Como vos prefieras!

2021-05-28 00:32 UTC, DylanMuszel commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiActivity.kt
> +        viewModel.createOrJoin()
Jajajaja te banco, por las dudas probá que funcione igual

2021-05-28 02:23 UTC, DylanMuszel commented on app/src/main/java/com/p2p/framework/SharedPreferencesUserInfoStorage.kt
> +    override fun getUserNameOrEmpty(): String = getUserName() ?: context.resources.getString(R.string.unknown)
![](https://media3.giphy.com/media/GrB9uThYsoU3C/giphy.gif)

2021-05-28 02:24 UTC, DylanMuszel approved these changes

2021-05-28 03:28 UTC, merged

2021-05-29 01:38 UTC, brendaboryszanski approved these changes