Adaptar diseño en pantallas de creación de Tutti Frutti
UTN-FRBA-Mobile/Play2Play pull request #15
Opened 2021-05-31 22:38 UTC by vaalecav

## Descripción

- Se adapta el diseño de la pantalla de creación de Tutti Frutti.
- Se cambió el diseño de los checkbox
- Se cambió el diseño de la selección de rondas, agrandando la vista.

## Card Jira

## Screenshots

2021-05-31 22:49 UTC, dylanmuszelml requested changes
Banco cómo quedó

2021-05-31 22:49 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/create/rounds/RoundsNumberFragment.kt
> +        dialog?.window?.setLayout(width, height);
No deberías tener algo tan fijo así, puede traer problemas en ciertos celulares, para qué lo querés?

2021-05-31 22:49 UTC, dylanmuszelml commented on app/src/main/res/drawable/circle_checkbox.xml
> +    <item android:drawable="@drawable/ic_circle_checkbox_unchecked" />
Como dato por si te interesa, acá si querés (y si mo me equivoco) podés sacar el state_checked="false" total el default ya es ese drawable.

2021-05-31 23:31 UTC, vaalecav commented on app/src/main/java/com/p2p/presentation/tuttifrutti/create/rounds/RoundsNumberFragment.kt
> +        dialog?.window?.setLayout(width, height);
Quería cambiar el tamaño del dialog, pero cuando lo modifico desde el layout no se modifica. Entendí que tenía que ver por el momento en que se crea tal vez?
Pero como no se modificaba, recaí en don google que me sugirió hacer esto.

Tenés alguna mejor manera de hacer esto? o sabés por qué me puede estar pasando? 🤗

2021-05-31 23:31 UTC, vaalecav commented on app/src/main/java/com/p2p/presentation/tuttifrutti/create/rounds/RoundsNumberFragment.kt
> +        dialog?.window?.setLayout(width, height);
Quería cambiar el tamaño del dialog, pero cuando lo modifico desde el layout no se modifica. Entendí que tenía que ver por el momento en que se crea tal vez?
Pero como no se modificaba, recaí en don google que me sugirió hacer esto.

Tenés alguna mejor manera de hacer esto? o sabés por qué me puede estar pasando? 🤗

2021-05-31 23:37 UTC, vaalecav commented on app/src/main/res/drawable/circle_checkbox.xml
> +    <item android:drawable="@drawable/ic_circle_checkbox_unchecked" />
totalmente si! Ahora lo ajusto

2021-05-31 23:42 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/create/rounds/RoundsNumberFragment.kt
> +        dialog?.window?.setLayout(width, height);
Pero qué cosa del dialog querés cambiar? O sea, lo mejor es que el dialog o se ajuste a su contenido o se ajuste a su contenedor. Cuál de las 2 querrías?

2021-06-01 00:36 UTC, vaalecav commented on app/src/main/java/com/p2p/presentation/tuttifrutti/create/rounds/RoundsNumberFragment.kt
> +        dialog?.window?.setLayout(width, height);
- seguimos charlando esto por chat - En resumen, dyl me explicó que al ajustar estos tamaños mediante porcentajes, muy probablemente quede bien en pantallas grandes, pero en celulares pequeños terminaría consumiendose la vista y siendo demasiado pequeña para mostrar todos los componentes.
Por eso siempre optamos por ajustar las medidas mediante dimens y no porcentajes.

2021-06-01 01:04 UTC, dylanmuszelml approved these changes

2021-06-02 23:15 UTC, dylanmuszelml approved these changes

2021-06-02 23:16 UTC, DylanMuszel approved these changes

2021-06-02 23:17 UTC, merged