Crear pantalla de review y manejo de puntos
UTN-FRBA-Mobile/Play2Play pull request #20
Opened 2021-06-11 00:30 UTC by vaalecav

## Descripcion

## Card Jira

## Screenshots

2021-06-17 20:45 UTC, vaalecav commented on app/src/main/res/layout/fragment_play_tutti_frutti.xml
>      <TextView
Si algune tiene una mejor manera de hacer esto (aplicar distintos estilos al mismo texto), pls cuenten como <3

2021-06-21 19:28 UTC, dylanmuszelml requested changes
Laburazo! Hermoso resuelto 👏🏼👏🏼👏🏼
Te marqué algunas cositas, pero sobre todo 2 boludeces:
- Tratá de nunca obtener el valor de un LiveData de un viewmodel desde un fragment, hacelo siempre desde el observe.
- Fijate que hace unos PRs agregué la extensión `requireValue` al livedata, tratá de usar eso en vez de `value!!`

2021-06-21 19:28 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/model/tuttifrutti/FinishedRoundPointsInfo.kt
> +    val wordsPoints: MutableList<Int>,
No puede ser inmutable esto? Y lo vas manejando con el .copy?

2021-06-21 19:28 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/review/TuttiFruttiReviewFragment.kt
> +            gameViewModel.finishedRoundInfos.value!!
Esto hay que observarlo y recién ahí pasarselo al view model.

Onda 
```
gameViewModel.actualRound.observe(viewLifecycleOwner, { viewModel.setActualRound(it) })
gameViewModel.finishedRoundInfos.observe(viewLifecycleOwner, { viewModel.setFinishedRoundInfos(it) })
```

2021-06-21 19:28 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/review/TuttiFruttiReviewFragment.kt
> +                    resources.getString(R.string.tf_enough_player, finishedRoundInfo.find { it.saidEnough }!!.player)
```suggestion
                    resources.getString(R.string.tf_enough_player, finishedRoundInfo.first { it.saidEnough }.player)
```

2021-06-21 19:28 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/review/TuttiFruttiReviewFragment.kt
> +        FinishRoundReview -> gameViewModel.setFinishedRoundPointsInfos(viewModel.finishedRoundPointsInfo.value!!)
El evento `FinishRoundReview` debería pasar el `finishedRoundPointsInfo`, no se debería agarrar desde el viewmodel. Onda
 ```suggestion
        is FinishRoundReview -> gameViewModel.setFinishedRoundPointsInfos(event.finishedRoundPointsInfo)
```

2021-06-21 19:28 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/review/TuttiFruttiReviewRoundAdapter.kt
> +        return position % (finishedRoundInfo.count() + 1)
Fantástico esto! Estaría bueno devolver una constante o un enum para hacerlo más claro.
Tener 
```
const val TITLE_TYPE = 0
const val WORD_TYPE = 1
```
y acá devolver 
```suggestion
        return if (position % (finishedRoundInfo.count() + 1) == 0) TITLE_TYPE else WORD_TYPE
```

Si no no termina de quedar claro 😅

2021-06-21 19:28 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/review/TuttiFruttiReviewRoundAdapter.kt
> +        }
Como tip para hacer toda esa `RecyclerViewHolderParameters` inmutable, si querés:

```suggestion
        val viewHolderParams: RecyclerViewHolderParameters
        val categoryIndex = getCategoryIndex(position)
        val viewCategory = getCategory(categoryIndex)

        if (viewIndex == 0) {
            viewHolderParams = RecyclerViewHolderParameters(category = viewCategory)
        } else {
            viewHolderParams = RecyclerViewHolderParameters(
                player = finishedRoundInfo[viewIndex - 1].player,
                word = finishedRoundInfo[viewIndex - 1].categoriesWords.getValue(viewCategory),
                points = finishedRoundPointsInfo.first {
                  it.player == viewHolderParams.player
                }.wordsPoints[categoryIndex]
        }
```

En caso de que prefieras dejarla como está, sí fijate de usar el `getValue` y el `first` en vez de `find` 😅

2021-06-21 19:28 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/review/TuttiFruttiReviewRoundAdapter.kt
> +        return finishedRoundInfo.first().categoriesWords.keys.toTypedArray()[categoryIndex]
keys es un set, me da miedo que le cambie el orden a las categories, sería mejor capaz:
```suggestion
        return finishedRoundInfo.first().categoriesWords.toList()[categoryIndex].first
```

2021-06-21 19:28 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/review/TuttiFruttiReviewRoundAdapter.kt
> +                10 -> {
sería más piola que 0, 5 y 10 sean constantes (MIN_SCORE, MIDDLE_SCORE (?) y MAX_SCORE, o algo así) para que no parezcan números random 😅

2021-06-21 19:28 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/review/TuttiFruttiReviewRoundAdapter.kt
> +                onChangeRoundPoints.invoke("add", viewHolderParams.player, getCategoryIndex(position))
Esto sería clave tenerlo de otra forma más simple, te lo comento más abajo 😃

2021-06-21 19:28 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/review/TuttiFruttiReviewViewModel.kt
> +    }
En vez de tener un único método se podrían pasar dos, onda `onAddRoundPoints` y `onSubstractRoundPoints` y también si no se podría tener una interfaz y pasarle la clase que implementa la interfaz, que en este caso sería el viewmodel. Pero tener un método que hable a través de strings lo que tiene que hacer me parece medio rari.

2021-06-21 19:28 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/review/TuttiFruttiReviewViewModel.kt
> +            }
```suggestion
            val pointsList = it.categoriesWords.map { playerResponse ->
                val categoryWords = getCategoryWords(playerResponse.key, finishedRoundInfos)
                getPointsForWord(playerResponse.value, actualRound.letter, categoryWords)
            }
```

2021-06-21 19:28 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/review/TuttiFruttiReviewViewModel.kt
> +        finishedRoundPointsInfo.value!!.forEach { it.totalPoints = it.wordsPoints.sum() }
```suggestion
        finishedRoundPointsInfo.requireValue().forEach { it.totalPoints = it.wordsPoints.sum() }
```

2021-06-21 23:36 UTC, vaalecav commented on app/src/main/java/com/p2p/model/tuttifrutti/FinishedRoundInfo.kt
> +    val categoriesWords: LinkedHashMap<Category, String>,
Porque no me dejaba acceder a cierta "posición" con el otro Map, y además mantiene el mismo orden en el cual fueron insertados los elementos.

2021-06-21 23:37 UTC, vaalecav commented on app/src/main/java/com/p2p/presentation/tuttifrutti/review/TuttiFruttiReviewFragment.kt
> +        FinishRoundReview -> gameViewModel.setFinishedRoundPointsInfos(viewModel.finishedRoundPointsInfo.value!!)
Genial!

2021-06-21 23:37 UTC, vaalecav commented on app/src/main/java/com/p2p/presentation/tuttifrutti/review/TuttiFruttiReviewRoundAdapter.kt
> +        return position % (finishedRoundInfo.count() + 1)
Re, ahi lo cambio 🤗

2021-06-21 23:37 UTC, vaalecav commented on app/src/main/java/com/p2p/presentation/tuttifrutti/review/TuttiFruttiReviewRoundAdapter.kt
> +        }
uuuuuuuy genial, muchas gracias!

2021-06-21 23:41 UTC, vaalecav commented on app/src/main/java/com/p2p/presentation/tuttifrutti/review/TuttiFruttiReviewRoundAdapter.kt
> +        return finishedRoundInfo.first().categoriesWords.keys.toTypedArray()[categoryIndex]
De uni 🤗

2021-06-21 23:41 UTC, vaalecav commented on app/src/main/java/com/p2p/presentation/tuttifrutti/review/TuttiFruttiReviewRoundAdapter.kt
> +                10 -> {
Coincido! Ahi lo cambio 🤗

2021-06-21 23:44 UTC, vaalecav commented on app/src/main/java/com/p2p/presentation/tuttifrutti/review/TuttiFruttiReviewViewModel.kt
> +    }
Genial 🤗

2021-06-22 00:00 UTC, vaalecav commented on app/src/main/java/com/p2p/model/tuttifrutti/FinishedRoundPointsInfo.kt
> +    val wordsPoints: MutableList<Int>,
Sipi, de una!

2021-06-22 00:39 UTC, vaalecav commented on app/src/main/java/com/p2p/presentation/tuttifrutti/review/TuttiFruttiReviewFragment.kt
> +            gameViewModel.finishedRoundInfos.value!!
Claro, lo hice asi al principio, pero el problema que tenia era que al llamar ` viewModel.initializeBaseRoundPoints()` no tengo estos valores inicializados, y rompia con nullPointer :(
Como sugeris manejar eso?

2021-06-23 22:10 UTC, vaalecav commented on app/src/main/java/com/p2p/presentation/tuttifrutti/review/TuttiFruttiReviewFragment.kt
> +            gameViewModel.finishedRoundInfos.value!!
Ahi fue el fix con lo que charlamos 🤗

2021-06-24 13:38 UTC, dylanmuszelml approved these changes
Solo una boludez 😅  Pero ya después mergeá! Quedó hermoso ♥️

2021-06-24 13:38 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/review/TuttiFruttiReviewRoundAdapter.kt
> +        if (viewType == 0) {
```suggestion
        if (viewType == TITLE_TYPE) {
```

2021-06-24 13:39 UTC, dylanmuszelml reviewed
Me di cuenta de unas boludeces más

2021-06-24 13:39 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/review/TuttiFruttiReviewViewModel.kt
> +        val elementToUpdate = updatedFinishedRoundPoints.find { it.player == player }!!
```suggestion
        val elementToUpdate = updatedFinishedRoundPoints.first { it.player == player }
```

2021-06-24 13:39 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/review/TuttiFruttiReviewViewModel.kt
> +        finishedRoundInfos!!.map{ Normalizer.normalize(it.categoriesWords[category].toString(), Normalizer.Form.NFD) }
```suggestion
    private fun getCategoryWords(category: Category, finishedRoundInfos: List< FinishedRoundInfo>) : List<String> =
        finishedRoundInfos.map{ Normalizer.normalize(it.categoriesWords[category].toString(), Normalizer.Form.NFD) }
```

2021-06-24 13:39 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/review/TuttiFruttiReviewViewModel.kt
> +        val elementToUpdate = updatedFinishedRoundPoints.find { it.player == player }!!
```suggestion
        val elementToUpdate = updatedFinishedRoundPoints.first { it.player == player }
```

2021-06-24 23:53 UTC, florencialipchak commented on app/src/main/java/com/p2p/presentation/tuttifrutti/review/TuttiFruttiReviewViewModel.kt
> +        }
Se podrían evitar los foreach con:

```
val roundInitialPoints = finishedRoundInfo.value!!.map {
            val pointsList = it.categoriesWords.map { playerResponse ->
                val categoryWords = getCategoryWords(playerResponse.key)
                getPointsForWord(playerResponse.value, actualRound.letter, categoryWords)
            }

            FinishedRoundPointsInfo(it.player, pointsList, pointsList.sum())
        }
```

2021-06-25 00:38 UTC, vaalecav commented on app/src/main/java/com/p2p/presentation/tuttifrutti/review/TuttiFruttiReviewViewModel.kt
> +        }
Hermoso!

2021-06-25 00:59 UTC, florlipchak approved these changes

2021-06-25 00:59 UTC, merged