Lobby
UTN-FRBA-Mobile/Play2Play pull request #21
Opened 2021-06-14 19:35 UTC by PadillaJuan

https://user-images.githubusercontent.com/16126261/121949053-6d3f8080-cd2e-11eb-99fd-56cd865f0a9d.mp4

2021-06-14 20:17 UTC, dylanmuszelml requested changes

2021-06-14 20:17 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/lobby/ServerLobbyFragment.kt
> +                if (it.size >= LOBBY_MIN_SIZE) gameBinding.startGame.isEnabled = true
Esto lo debería manejar el viewmodel del fragment. Capaz acá podrías llamar a un método del viewmodel estilo `onPlayersChanged(list)` y que ahí haga esto.

2021-06-14 20:17 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/lobby/ServerLobbyViewModel.kt
> +    val goToPlayButtonEnabled: LiveData<Boolean> = _goToPlayButtonEnabled
Acá tenés estos livedata que no los usás, a esto deberías modificarle la lógica para habilitar el botón.

2021-06-14 20:17 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/lobby/ClientLobbyViewModel.kt
> +class ClientLobbyViewModel: BaseViewModel<LobbyEvent>() {}
```suggestion
class ClientLobbyTuttiFruttiViewModel: BaseViewModel<LobbyEvent>() {}
```

2021-06-14 20:17 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/lobby/ConnectedPlayersAdapter.kt
> +class ConnectedPlayersAdapter: RecyclerView.Adapter<ConnectedPlayersAdapter.ViewHolder>() {
```suggestion
class ConnectedPlayersTuttiFruttiAdapter: RecyclerView.Adapter<ConnectedPlayersAdapter.ViewHolder>() {
```

2021-06-14 20:17 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/lobby/ServerLobbyFragment.kt
> +class ServerLobbyFragment: BaseGameFragment<
```suggestion
class ServerLobbyTuttiFruttiFragment: BaseGameFragment<
```

2021-06-14 20:17 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/lobby/ServerLobbyViewModel.kt
> +class ServerLobbyViewModel: BaseViewModel<LobbyEvent>() {
```suggestion
class ServerLobbyTuttiFruttiViewModel: BaseViewModel<LobbyEvent>() {
```

2021-06-14 20:17 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/lobby/lobbyEvent.kt
> +object GoToPlay : LobbyEvent()
Esto lo usás en algún lado?

2021-06-14 20:17 UTC, dylanmuszelml commented on app/src/main/res/layout/fragment_server_lobby.xml
> +    <!-- PR REVIEW: esto no aplica un margin top, alguien sabe por que?-->
Porque lo estás atando al `progressBar_cyclic` que no existe 😓 Me sorprende que no te rompa directamente jajaja
```suggestion
        app:layout_constraintTop_toBottomOf="@id/guideline_top"
        app:layout_constraintStart_toStartOf="@id/guideline_begin" />
```

2021-06-14 20:17 UTC, dylanmuszelml commented on app/src/main/res/layout/fragment_server_lobby.xml
> +        android:textColor="@color/colorLink"
Una boludez 😅 Pero yo a esto lo dejaría en negro

2021-06-17 00:11 UTC, vaalecav reviewed
Nice! Adhiero a los comments de dyl! 

Si podes agregar un screenshot/video de la pantalla del lobby del cliente genial 🤗

2021-06-17 00:11 UTC, vaalecav commented on app/src/main/java/com/p2p/presentation/tuttifrutti/lobby/ServerLobbyFragment.kt
> +                if (it.size >= LOBBY_MIN_SIZE) gameBinding.startGame.isEnabled = true
Esoo, todo lo que modifique "la data" tiene que ir directo al view model 🤗

2021-06-17 00:11 UTC, vaalecav commented on app/src/main/res/layout/fragment_server_lobby.xml
> +    <!-- PR REVIEW: esto no aplica un margin top, alguien sabe por que?-->
F, la copy pasta del `fragment_client_lobby` 😆

2021-06-17 00:11 UTC, vaalecav commented on app/src/main/res/layout/fragment_server_lobby.xml
> +
```suggestion
```

2021-06-17 05:11 UTC, PadillaJuan commented on app/src/main/res/layout/fragment_server_lobby.xml
> +    <!-- PR REVIEW: esto no aplica un margin top, alguien sabe por que?-->
exactamente eso jajaja

2021-06-17 06:11 UTC, PadillaJuan commented on app/src/main/java/com/p2p/presentation/tuttifrutti/lobby/lobbyEvent.kt
> +object GoToPlay : LobbyEvent()
Quedó duplicado de otra cosa :( Debería dejar la sealed class para respetar la convención?

2021-06-17 06:54 UTC, PadillaJuan commented on app/src/main/java/com/p2p/presentation/tuttifrutti/lobby/ServerLobbyFragment.kt
> +                if (it.size >= LOBBY_MIN_SIZE) gameBinding.startGame.isEnabled = true
No entendí esto :( En este caso tengo que actualizar el adapter para que se dibujen los usuarios conectados y necesito el binding para habilitar el boton. El VM no tiene nada de eso, debería pasarle todo como parámetro?

2021-06-17 07:43 UTC, PadillaJuan commented
Ahí subí un nuevo video mostrando el lobby y además, mostrando el cambio en el loader, agregando el texto de "esperando jugadores"

2021-06-17 20:52 UTC, DylanMuszel commented on app/src/main/java/com/p2p/presentation/tuttifrutti/lobby/ServerLobbyFragment.kt
> +                if (it.size >= LOBBY_MIN_SIZE) gameBinding.startGame.isEnabled = true
Nono, la cosa sería que tengas el estado del botón como un observable del viewmodel.
Sería

viewmodel
```
private val _isContinueButtonEnabled = MutableLiveData(false)
val isContinueButtonEnabled: LiveData<Boolean> = _isContinueButtonEnabled

fun updatePlayers(val players: List<String>) {
     _isContinueButtonEnabled.value = players.size >= LOBBY_MIN_SIZE
} 
```

fragment
```
gameViewModel.players.observe(viewLifecycleOwner) {                
      connectedPlayersAdapter.players = it
      viewModel.updatePlayers(it)
}
viewModel.isContinueButtonEnabled.observe(viewLifecycleOwner) { binding.button.isEnabled = it }
```

Se entiende con esto?

2021-06-17 20:52 UTC, DylanMuszel commented on app/src/main/java/com/p2p/presentation/tuttifrutti/lobby/lobbyEvent.kt
> +object GoToPlay : LobbyEvent()
Para mí hace falta, mandale Unit en el event y listo

2021-06-17 21:52 UTC, PadillaJuan commented on app/src/main/java/com/p2p/presentation/tuttifrutti/lobby/ServerLobbyFragment.kt
> +                if (it.size >= LOBBY_MIN_SIZE) gameBinding.startGame.isEnabled = true
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, sisi, perfecto. como estaban marcadas 4 lineas me confundí sobre que debería o no debería estar y donde jajaja tenkiu <3

2021-06-18 22:19 UTC, vaalecav approved these changes
Habria que chequear lo del error ese, pero despues todo ok :) 🥳

2021-06-18 22:19 UTC, vaalecav commented on app/src/main/java/com/p2p/presentation/tuttifrutti/lobby/ServerTuttiFruttiLobbyFragment.kt
> +        TuttiFruttiViewModel>() {
```suggestion
        TuttiFruttiViewModel>() {
        
```

2021-06-18 22:19 UTC, vaalecav commented on app/src/main/java/com/p2p/presentation/tuttifrutti/lobby/ServerTuttiFruttiLobbyFragment.kt
> +        gameBinding.startGameButton.isEnabled = false
Esto deberiamos setearlo en el init del view model

2021-06-18 22:19 UTC, vaalecav commented on app/src/main/java/com/p2p/presentation/tuttifrutti/lobby/ServerTuttiFruttiLobbyFragment.kt
> +            is GoToPlay -> Unit
Por que el unit? No deberia hacer algo el evento?

2021-06-18 22:19 UTC, vaalecav commented on app/src/main/java/com/p2p/presentation/tuttifrutti/lobby/ServerTuttiFruttiLobbyViewModel.kt
> +    fun updatePlayers(players: List<String>) {
```suggestion
    fun updateContinueButtonStatus(players: List<String>) {
```

2021-06-21 19:34 UTC, dylanmuszelml approved these changes
![](https://media4.giphy.com/media/cdNSp4L5vCU7aQrYnV/giphy.gif)

2021-06-21 19:34 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/lobby/ServerTuttiFruttiLobbyFragment.kt
> +        gameBinding.startGameButton.isEnabled = false
De hecho se puede setear directo desde el xml 😅

2021-06-21 19:34 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/lobby/ClientTuttiFruttiLobbyFragment.kt
> +        gameViewModel.startConnection()  // TODO Check Fragment without an activity on init {}
Aaaaah, ya entendí lo que decías, está bien que esto esté acá. No tiene que estar en el init

2021-06-24 20:31 UTC, PadillaJuan commented on app/src/main/java/com/p2p/presentation/tuttifrutti/lobby/ServerTuttiFruttiLobbyFragment.kt
> +            is GoToPlay -> Unit
Oh, había entendido eso de lo que habia comentado dylan

> Para mí hace falta, mandale Unit en el event y listo

2021-06-30 14:18 UTC, dylanmuszelml approved these changes

2021-06-30 22:23 UTC, vaalecav approved these changes
🐼

2021-06-30 22:27 UTC, merged