added loading screen
UTN-FRBA-Mobile/Play2Play pull request #22
Opened 2021-06-17 02:11 UTC by brendaboryszanski

Se agrega el loading
![WhatsApp Image 2021-06-16 at 23 09 57](https://user-images.githubusercontent.com/18487966/122320104-15547580-cef8-11eb-971d-7a9ea0123d93.jpeg)

2021-06-17 08:11 UTC, PadillaJuan commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiViewModel.kt
> +    protected val _nextSteploadingText = MutableLiveData<String>()
_nextStepLoadingText así queda bien el camel <3

2021-06-17 08:13 UTC, PadillaJuan approved these changes

2021-06-17 17:53 UTC, vaalecav commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiActivity.kt
> +        }
No entiendo por qué es de tipo `MutableLiveData`, por qué estamos observando este texto? No podríamos dejarlo estático en la view y listo?

2021-06-17 19:38 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiActivity.kt
> +        }
La idea es que sea un loading que dsp cunado vayas a mandar quien gano etc sea modifique ese texto pense.. como que podes tener mas de la misma pantalla con el mismo texto

2021-06-17 20:47 UTC, DylanMuszel commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiActivity.kt
> +        }
Okey, iba a decir que estaba de acuerdo con vale, pero después entendí lo de reutilizar la pantalla y me parece piola. Lo que sí, no lo haría como algo separado, si no que lo podría como parte del `isLoading` siendo un Pair, una clase o algo así. Si no me parece que queda colgado.

2021-06-18 18:50 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiActivity.kt
> +        }
genial!

2021-06-18 22:25 UTC, vaalecav approved these changes
Nice 🤗

2021-06-21 14:44 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiActivity.kt
> +        }
@DylanMuszel @vaalecav ahi lo modifique!

2021-06-21 14:45 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiActivity.kt
> +        }
vale y juan ya aprobaron
@DylanMuszel si das el ok mergeo!

2021-06-21 19:40 UTC, dylanmuszelml reviewed
Me marea mucho el uso del copy, porque no le encuentro el sentido, como que termina quedando super acoplado al momento en el que se manda ese mensaje y que no cambiemos algo y se mande otro is loading en el medio porque lo va a romper

2021-06-21 19:40 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiViewModel.kt
> +        _loading.value = requireNotNull(loading.value).copy(loadingText = nextStepLoadingText)
Me marea el uso del copy acá, o sea no estás modificando algo de la clase existente, estás creando una nueva. Onda acá ni siquiera debería cambiar el loading, o sí?

2021-06-21 19:40 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiViewModel.kt
> +        _loading.value = requireNotNull(loading.value).copy(isLoading = true)
Y acá lo mismo de arriba, acá capaz deberías recibir ese mensaje que decías y poner `_loading.value = Loading(isLoading = true, message = message)`. O quizás recibir ese mensaje en el init del viewmodel directamente o algo así 😕

2021-06-21 19:40 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiViewModel.kt
> +        _loading.value = requireNotNull(loading.value).copy(isLoading = true)
Same al de arriba

2021-06-25 22:41 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiViewModel.kt
> +        _loading.value = requireNotNull(loading.value).copy(loadingText = nextStepLoadingText)
tenes razon

2021-06-25 22:41 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiViewModel.kt
> +        _loading.value = requireNotNull(loading.value).copy(isLoading = true)
totalmente

2021-06-25 22:41 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiViewModel.kt
> +        _loading.value = requireNotNull(loading.value).copy(isLoading = true)
yeaaa

2021-06-26 00:43 UTC, brendaboryszanski commented
@DylanMuszel @vaalecav @PadillaJuan ahi actualice...
Puse que se le mande el mensaje al decir basta para mi basta para todos para que no quede confuso lo del nextStepLoadingText... eso era raro jajja

2021-06-26 00:44 UTC, brendaboryszanski commented
si queremos a futuro se le puede mandar el nombre de quien dijo basta o lo que sea :)

2021-06-26 14:13 UTC, florlipchak commented on app/src/main/java/com/p2p/model/tuttifrutti/message/TuttiFruttiEnoughForMeEnoughForAllMessage.kt
> +class TuttiFruttiEnoughForMeEnoughForAllMessage(val waitingMessage: String) : Message(TYPE) {
no termino de entender qué beneficio nos da mandar esto en el mensaje, si se saca de las resources para todos los dispositivos. Habíamos dicho de mantener los mensajes lo más cortos posibles para disminuir problemas de performance. Se me ocurre de última tener algo como un enum o un mapa en las resources y que sea 
1 -> "un mensaje"
2 -> "otro mensaje" 
y se mande solo el código o algo así.

2021-06-27 15:32 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/model/tuttifrutti/message/TuttiFruttiEnoughForMeEnoughForAllMessage.kt
> +class TuttiFruttiEnoughForMeEnoughForAllMessage(val waitingMessage: String) : Message(TYPE) {
si.. lo habia puesto porque necesitaba del fragment.. Peor me cierra mas hacer un repository

2021-06-27 20:28 UTC, dylanmuszelml requested changes

2021-06-27 20:28 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiViewModel.kt
> -        _isLoading.value = true
El server también tiene que mostrar un loading!

2021-06-27 20:28 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiViewModel.kt
> -        _isLoading.value = true
Same

2021-06-27 20:28 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/ServerTuttiFruttiViewModel.kt
> +            _loadingScreen.value = HiddenLoadingScreen
La pantalla de loading se tiene que ocultar recién cuando se inicializa la pantalla de review, si no va a haber un efecto rari porque va a ocultar el loading, te va a mostrar la pantalla del juego y recién después va a mostrar la review.

2021-06-27 20:28 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/review/TuttiFruttiReviewFragment.kt
> -        gameViewModel.stopLoading()
Como dije arriba, esto tiene que quedar cómo estaba antes. Por alguna razón lo cambiaste?

2021-06-27 20:28 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/framework/LoadingTextLocalResourcesSource.kt
> +        textByMessage[messageType] ?: context.resources.getString(R.string.default_loading_text)
No sería mejor que el default sea vacío?

2021-06-28 12:39 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiViewModel.kt
> -        _isLoading.value = true
el server pasaba q quedaba rari porque se mostraba una pantalla un seg q no se llegaba a leer....

2021-06-28 13:09 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiViewModel.kt
> -        _isLoading.value = true
Es que no sé si tiene que decir algo, pero una pantalla de loading hay que mostrar porque ahora te tardó un segundo, pero no necesariamente tarda eso, tiene que esperar a que todes les clientes le manden las palabras y puede tardar un poco más

2021-06-29 20:00 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiViewModel.kt
> -        _isLoading.value = true
joya le pongo vacio

2021-06-29 20:08 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/tuttifrutti/ServerTuttiFruttiViewModel.kt
> +            _loadingScreen.value = HiddenLoadingScreen
jaaja daleee

2021-06-29 20:09 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiViewModel.kt
> -        _isLoading.value = true
oudated

2021-06-29 20:10 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/tuttifrutti/review/TuttiFruttiReviewFragment.kt
> -        gameViewModel.stopLoading()
lo habia sacado para que sea en el otro lugar, pero tenes razon que queda mejor aca

2021-06-30 13:15 UTC, dylanmuszelml approved these changes

2021-06-30 23:45 UTC, merged