Tutti frutti select categories
UTN-FRBA-Mobile/Play2Play pull request #3
Opened 2021-05-17 15:09 UTC by brendaboryszanski

Se crea la primera pantalla para crear el juego.

Aclaraciones:

- En el recycleView de los radiobuttons, como el recycle justamente recicla los templates, se mambea bastante con los seleccionados, busque varias soluciones en internet pero ninguna funcionaba, por lo que implemente la lista con todas las categorias y que cada una conozca si esta seleccionada o no, sacandole la responsabilidad de hacerlo al recycle.

2021-05-17 15:13 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/tuttifrutti/create/CategoriesAdapter.kt
> +class CategoriesAdapter(private val onSelectedChanged: (Category, Boolean) -> Unit) : RecyclerView.Adapter<CategoriesAdapter.ViewHolder>() {
El adapter del recycleView de un radioButon se podria extraer por si lo volvemos a necesitar, pero quizas convenga hacerlo al necesitar otro, ya que puede complejizar en un ppio la comprension de este

2021-05-17 15:14 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/tuttifrutti/create/Category.kt
> +enum class Category(@StringRes val nameRes: Int) {
La idea es agarrarlo desde el array de resources, pero no encontre como pasarlo en el enum

2021-05-17 17:12 UTC, dylanmuszelml requested changes

2021-05-17 17:12 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/create/SelectedCategoriesAdapter.kt
> +        }
Lo mismo que en el otro adapter, no entiendo la razón de tener un `selected` cuando no hay un solo seleccionado.

2021-05-17 17:12 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/create/SelectedCategoriesAdapter.kt
> +                selected = category
```suggestion
                onDeleteCategory(category)
```

2021-05-17 17:12 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/storage/InternalStorage.kt
> +class InternalStorage {
![](https://media1.giphy.com/media/3WmWdBzqveXaE/giphy.gif)
¿Qué es esto? jajaja

2021-05-17 17:12 UTC, dylanmuszelml commented on app/src/main/res/drawable-xxhdpi/border.xml
> +<?xml version="1.0" encoding="utf-8"?>
Supongo que esto se irá cuando agregues los chips, pero 3 cosas:
1. El nombre debería ser más claro, onda no es simplemente un borde. Sería algo como bordered_rectangle.
2. Fijate que lo pusiste adentro de la carpeta `-xxhdpi`. Debería estar en drawable a secas.
3. Estaría bueno que todas las dimensiones no estén acá sino que usen los @dimen

2021-05-17 17:12 UTC, dylanmuszelml commented on app/src/main/res/layout/fragment_create_tutti_frutti.xml
> +        />
Toda esta lógica estaría bueno separarla y dejar algo base armado para el resto de las pantallas. Pero armemos una tarea en Jira y dejemoslo para más adelante,.

2021-05-17 17:12 UTC, dylanmuszelml commented on app/src/main/res/layout/fragment_create_tutti_frutti.xml
> +        android:id="@+id/categories_recycle"
```suggestion
        android:id="@+id/categories_recycler"
```

2021-05-17 17:12 UTC, dylanmuszelml commented on app/src/main/res/layout/fragment_create_tutti_frutti.xml
> +        android:layout_weight="0.7"
¿Por qué esto?

2021-05-17 17:12 UTC, dylanmuszelml commented on app/src/main/res/layout/fragment_create_tutti_frutti.xml
> +            android:id="@+id/categories_selected_recycle"
```suggestion
            android:id="@+id/categories_selected_recycler"
```

2021-05-17 17:12 UTC, dylanmuszelml commented on app/src/main/res/layout/fragment_create_tutti_frutti.xml
> +            tools:orientation="horizontal"
Agreguemosle el fadingEdge así sombrea el principio y el final cuando hay muchas categorías

2021-05-17 17:12 UTC, dylanmuszelml commented on app/src/main/res/layout/view_category_item.xml
> +        android:alpha="0.8"
Esto lo puse arriba, por qué se les cambia el alpha?

2021-05-17 17:12 UTC, dylanmuszelml commented on app/src/main/res/layout/view_category_item.xml
> +            app:layout_constraintTop_toTopOf="parent">
Por qué el linear?

2021-05-17 17:12 UTC, dylanmuszelml commented on app/src/main/res/layout/view_category_item.xml
> +                android:text="Category"/>
```suggestion
                tools:text="Category"/>
```

2021-05-17 17:12 UTC, dylanmuszelml commented on app/src/main/res/layout/view_selected_category_item.xml
> +        android:text="Selected category"
```suggestion
        tools:text="Selected category"
```

2021-05-17 17:12 UTC, dylanmuszelml commented on app/src/main/res/layout/view_selected_category_item.xml
> +        android:paddingEnd="16dp"/>
Usemos las dimens 😄

2021-05-17 17:12 UTC, dylanmuszelml commented on app/src/main/res/values/colors.xml
> +    <color name="colorRed">@color/red</color>
Para qué es esto? No le veo el sentido 🤔

2021-05-17 17:12 UTC, dylanmuszelml commented on app/src/main/res/values/dimens.xml
> +    <dimen name="button_big">200dp</dimen>
Qué es esto?

2021-05-17 17:13 UTC, dylanmuszelml commented
Ah, algo que me olvidé de comentar. Porfa tengamos en cuenta formatear el código (Cmd + option + L) que si no cada vez que lo toquemos vamos a tener cambios y evitar dobles enters 🙏🏼 .

2021-05-17 18:48 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/data/tuttifrutti/CategoriesSource.kt
> +}
Listo! habia malentendido esto de categoriesSource jajaj ahi puse las categorias ahi

2021-05-17 18:48 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/data/tuttifrutti/CategoriesSource.kt
> +/** This interface brings the capacity to save user info into some storage. */
done!

2021-05-17 18:49 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/data/tuttifrutti/TuttiFruttiRepository.kt
> +    }
jajaja done

2021-05-17 18:50 UTC, brendaboryszanski commented on app/src/main/res/values/categories.xml
> +    </string-array>
ahi borre los names

2021-05-17 18:53 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/framework/CategoriesLocalResourcesSource.kt
> +}
sisi, l cambie

2021-05-17 18:53 UTC, brendaboryszanski commented on app/src/main/res/values/colors.xml
> +    <color name="colorRed">@color/red</color>
Queria poner el boton de eliminar en rojo, pero al final lo sacamos asi que lo vuelo

2021-05-17 18:53 UTC, brendaboryszanski commented on app/src/main/res/values/dimens.xml
> +    <dimen name="button_big">200dp</dimen>
era cuando ponia el boton de eliminar, pero lo vole asi que lo vuelo

2021-05-17 18:57 UTC, brendaboryszanski commented
> Ah, algo que me olvidé de comentar. Porfa tengamos en cuenta formatear el código (Cmd + option + L) que si no cada vez que lo toquemos vamos a tener cambios y evitar dobles enters 🙏🏼 .

listo!! le formatie todo

2021-05-17 19:01 UTC, brendaboryszanski commented on app/src/main/res/layout/view_selected_category_item.xml
> +        android:paddingEnd="16dp"/>
no se poruqe quedo choteado

2021-05-17 19:03 UTC, brendaboryszanski commented on app/src/main/res/values/strings.xml
> +    <string name="tf_categories_colours">Colores</string>
done

2021-05-17 19:22 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/tuttifrutti/create/CategoriesAdapter.kt
> +        }
volado categoriesData

2021-05-17 19:23 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/tuttifrutti/create/CategoriesAdapter.kt
> +        }
sip

2021-05-17 19:23 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/tuttifrutti/create/CategoriesAdapter.kt
> +    private fun getBackgroundColour(index: Int) = if(index.isEven()) backgroundPrimaryColour else backgroundSecondaryColour
jajja siii

2021-05-17 19:24 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/tuttifrutti/create/CategoriesAdapter.kt
> +            item.setBackgroundColor(ContextCompat.getColor(itemView.context, categoryData.backgroundColour))
ssiiii

2021-05-17 19:24 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/tuttifrutti/create/CategoriesAdapter.kt
> +            item.setBackgroundColor(ContextCompat.getColor(itemView.context, categoryData.backgroundColour))
era poruqe al ppio se mambeaba todo

2021-05-17 19:27 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/tuttifrutti/create/CategoriesAdapter.kt
> +            }
como lo deje ahora ahi ya tengo el valor, cuando lo saque recien y puse arriba el .isSelected se mambea.. no enitendo bien poruqe

2021-05-17 19:27 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/tuttifrutti/create/CategoriesAdapter.kt
> +            item.isChecked = categoryData.isSelected
jajaj si

2021-05-17 19:33 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/tuttifrutti/create/CreateTuttiFruttiViewModel.kt
> +        }
No puedo, necesito el booleano poruqe como es un liveData necesito que cuando lo tocas se cambie, entonces si lo toco dos veces
el selected no cambia, entonces necesito un booleano o algo que cambie (podria ser un int o cualquier cosa) pero para que se entere el viewModel que cambio

2021-05-17 19:35 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/tuttifrutti/create/CreateTuttiFruttiViewModel.kt
> +    fun categoriesCountIsValid() = selectedCategories.value?.size?.let { it >= 5 } ?: false
jajajaj genial

2021-05-17 19:36 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/tuttifrutti/create/CreateTuttiFruttiViewModel.kt
> +    fun categoriesCountIsValid() = selectedCategories.value?.size?.let { it >= 5 } ?: false
que es THRESHOLD?

2021-05-17 19:36 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/tuttifrutti/create/CreateTuttiFruttiViewModel.kt
> +            repository.setCategories(selectedCategories.value!!)
para nada jeje borrado

2021-05-17 19:36 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/tuttifrutti/create/CreateTuttiFruttiViewModelFactory.kt
> +        .newInstance(TuttiFruttiRepository(CategoriesLocalResourcesSource(listOf())))
siii

2021-05-17 21:46 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/tuttifrutti/create/CategoriesAdapter.kt
> +            }
no entendia bien el concepto del liveData jaja pensaba que tenia que estar si o si

2021-05-17 21:49 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/storage/InternalStorage.kt
> +class InternalStorage {
JAJAJAAJJAJAJA, lo vimos en clase, en un ppio lo iba a usar para persistir las categorias que al pedo, pero lo deje por si tenemos que usarlo, es para guardar en un archivo

2021-05-17 21:49 UTC, brendaboryszanski commented on app/src/main/res/drawable-xxhdpi/border.xml
> +<?xml version="1.0" encoding="utf-8"?>
sisisi igual lo vuelo con el chips. en realidad no estaba pudiendo poner un borde pero como estaba mal el disenio no le di mucha bola, es lo qeu faltaba hacer

2021-05-17 21:51 UTC, brendaboryszanski commented on app/src/main/res/layout/fragment_create_tutti_frutti.xml
> +        />
como un layout, me re parece, ahora creo el jira

2021-05-17 21:54 UTC, brendaboryszanski commented on app/src/main/res/layout/fragment_create_tutti_frutti.xml
> +        android:layout_weight="0.7"
no se me mostraba algo, y me sugeria que lo ponga, pero lo saque y no cambio, asi que es innecesario

2021-05-17 21:56 UTC, brendaboryszanski commented on app/src/main/res/layout/fragment_create_tutti_frutti.xml
> +            tools:orientation="horizontal"
hermoso, no lo veo mucho pero bueno jaja, onda ni se ve casi

2021-05-17 21:56 UTC, brendaboryszanski commented on app/src/main/res/layout/view_category_item.xml
> +        android:alpha="0.8"
me lo sugeria el intellij, jaja ahi lo borro

2021-05-17 21:57 UTC, brendaboryszanski commented on app/src/main/res/layout/view_category_item.xml
> +        android:alpha="0.8"
que es el alpha
?

2021-05-17 21:57 UTC, brendaboryszanski commented on app/src/main/res/layout/view_category_item.xml
> +            app:layout_constraintTop_toTopOf="parent">
con el constraint no me estaba saliendo...
me pongo como tarea cambiarlo y probar de nuevo :)

2021-05-18 01:55 UTC, florencialipchak approved these changes
:clap::clap::clap:

2021-05-18 19:09 UTC, dylanmuszelml requested changes
Genial laburo! Solo una boludez más que te diste cuenta el otro día

2021-05-18 19:09 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/home/games/GamesViewModel.kt
> +        dispatchSingleTimeEvent(GoToCreateTuttiFrutti)
Acá está lo que te diste cuenta el otro día 😅 
```suggestion
        when(selectedGame) {
            TUTTI_FRUTTI -> dispatchSingleTimeEvent(GoToCreateTuttiFrutti)
        }
```

2021-05-18 19:09 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/storage/InternalStorage.kt
> +class InternalStorage {
Jajajaj yo lo sacaría, no me imagino un caso en el que lo usemos y solo hace ruido

2021-05-18 19:09 UTC, dylanmuszelml commented on app/src/main/res/layout/fragment_create_tutti_frutti.xml
> +            tools:orientation="horizontal"
Jajaj sí, es chiquito pero da un efecto bastante más smooth que que simplemente desaparezca la vista 😅

2021-05-18 19:31 UTC, brendaboryszanski commented
Borre el internalStorage

2021-05-18 19:34 UTC, brendaboryszanski commented
Y deshabilite el boton de crear si no hay juego seleccionado

2021-05-18 19:55 UTC, dylanmuszelml approved these changes

2021-05-18 20:06 UTC, DylanMuszel approved these changes
Ahora sí jajaj

2021-05-20 22:19 UTC, merged