Join and create game
UTN-FRBA-Mobile/Play2Play pull request #39
Opened 2021-07-13 23:32 UTC by brendaboryszanski

Se hace la pantalla de creacion del juego y base del impostor

Se hace contra DEV asi mantenemos main con el tuti frutti
![WhatsApp Video 2021-07-11 at 15 32 56](https://user-images.githubusercontent.com/18487966/125206604-799bf800-e25e-11eb-8745-a9e7ed3eed19.gif)

Tambien se hace el lobby comun para tutti fruti e impostor

2021-07-14 00:01 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/impostor/ClientImpostorViewModel.kt
> +    override fun startGame() = goToPlay()
Todo esto en el siguiente PR pasa a estar en el viewmodel del impostor, y este queda vacio

2021-07-14 00:05 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/impostor/ServerImpostorViewModel.kt
> +    override fun createGame(word: String) {
Esto en el pr que viene se va de aca y pasa al de ambos para no tener que overridear todo

2021-07-14 23:33 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/clientlobby/ServerLobbyFragment.kt
> +class ServerLobbyFragment(override val gameViewModel: GameViewModel) : BaseGameFragment<
Me acuerdo que no tienen que tener constructores, pero si le pongo el byActivityViewModel rompe todo, y no se lo puedo pasar como bundle porque no es parcelable... etnonces lo deje asi, acepto sugerencias... idem en el ClientLobbyFragment

2021-07-17 00:59 UTC, dylanmuszelml requested changes

2021-07-17 00:59 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/basegame/GameViewModel.kt
> +    fun otherPlayers(): List<String>? =
```suggestion
    fun getOtherPlayers(): List<String>? =
```

2021-07-17 00:59 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/clientlobby/ClientLobbyFragment.kt
> +        ClientLobbyViewModel,
Estaría bueno de hacer un BaseGameFragment que no necesite de viewmodel, porque ya van varios (y van a seguir pasando) que no tienen necesidad de tener viewmodel.

2021-07-17 00:59 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/clientlobby/ServerLobbyFragment.kt
> +class ServerLobbyFragment(override val gameViewModel: GameViewModel) : BaseGameFragment<
Sí, como decís, esto no puede tener constructores, porque hay momentos en que el celular mata el fragment y lo vuelve a construir y lo hace con un constructor vacío.
Esto sí o sí hay que hacerlo con el `by activityViewModels()`. Y por lo que veo, sí o sí va a tener que haber una implementación para cada juego que al menos implemente eso, ya que es la única forma que se me ocurre.

2021-07-17 00:59 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/home/games/GamesAdapter.kt
> +        val (viewColor, textViewColor) =
Me gustó esto 😃

2021-07-17 00:59 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/home/games/GamesAdapter.kt
> +            else Pair(R.color.colorPrimaryVariant, R.color.colorPrimary)
```suggestion
            if (index.isEven()) R.color.colorSecondaryVariant to R.color.colorSecondary
            else R.color.colorPrimaryVariant to R.color.colorPrimary
```

2021-07-17 00:59 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/impostor/ImpostorActivity.kt
> +    }
Capaz se podría dejar esto como implementación base del GameActivity, qué pensás?

2021-07-17 00:59 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/impostor/ServerImpostorViewModel.kt
> +    override fun createGame(word: String) {
Iba a decir justamente esto, genial :)

2021-07-17 00:59 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/impostor/ImpostorViewModel.kt
> +    }
No sé si lo cambiaste en el próximo PR, pero no le daría bola a esto, al fin y al cabo si se pierde la conexión no hay problema total una vez arrancado no se tienen que mandar mensajes.

2021-07-17 00:59 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/impostor/ServerImpostorViewModel.kt
> +        return players.shuffled().first()
```suggestion
        return players.random()
```

2021-07-17 00:59 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/impostor/create/CreateImpostorFragment.kt
> +            players.joinToString(", ")
El ", " es el default :)
```suggestion
            players.joinToString()
```

2021-07-17 00:59 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/impostor/create/CreateImpostorFragment.kt
> +        else resources.getString(R.string.lobby_no_players_yet)
Por si te interesa, una forma que me parece a mí más linda es:
```suggestion
        val text = players
            ?.takeUnless { it.isEmpty() }
            ?.joinToString()
            ?: resources.getString(R.string.lobby_no_players_yet)
```

2021-07-17 00:59 UTC, dylanmuszelml commented on app/src/main/res/layout/fragment_create_impostor.xml
> +        app:layout_constraintTop_toTopOf="parent" />
Todos estos deberían estar atados a los guidelines

2021-07-17 00:59 UTC, dylanmuszelml commented on app/src/main/res/layout/fragment_create_impostor.xml
> +        app:layout_constraintRight_toRightOf="parent"
Same

2021-07-17 00:59 UTC, dylanmuszelml commented on app/src/main/res/layout/fragment_create_impostor.xml
> +        app:layout_constraintTop_toTopOf="parent" />
((y si podés usá start_toStart y end_toEnd en vez de left y right))

2021-07-17 00:59 UTC, dylanmuszelml commented on app/src/main/res/layout/fragment_create_impostor.xml
> +        app:layout_constraintRight_toRightOf="parent" />
Same

2021-07-17 00:59 UTC, dylanmuszelml commented on app/src/main/res/layout/fragment_create_impostor.xml
> +        android:layout_width="@dimen/text_field_size"
Me hace mucho ruido que esto tenga un size fijo, lo hiciste por alguna razón específica?

2021-07-17 00:59 UTC, dylanmuszelml commented on app/src/main/res/layout/fragment_create_impostor.xml
> +        android:inputType="textVisiblePassword"
Esto no hace falta que sea textVisiblePassword, eso es para que no aparezcan sugerencias en el tutti frutti.

2021-07-17 00:59 UTC, dylanmuszelml commented on app/src/main/res/layout/fragment_create_impostor.xml
> +        app:layout_constraintRight_toRightOf="parent"
Same lo de arriba

2021-07-17 00:59 UTC, dylanmuszelml commented on app/src/main/res/layout/fragment_create_impostor.xml
> +        app:layout_constraintRight_toRightOf="parent"/>
Same

2021-07-17 00:59 UTC, dylanmuszelml commented on app/src/main/res/values/strings.xml
> +    <string name="im_write_key_word">Ingrese palabra clave</string>
```suggestion
    <string name="im_write_key_word">Ingrese la palabra clave</string>
```

2021-07-17 01:01 UTC, dylanmuszelml commented on app/src/main/res/layout/fragment_create_impostor.xml
> +        android:layout_width="@dimen/text_field_size"
Ahí vi el video, imagino que es para que no sea tan grande. Tiene sentido, pero no es una buena práctica poner tamaños fijos en los widths, puede traer problemas en otros celulares, pero podría pasar para este caso. Lo que sí, no haría que la dimen sea algo genérico sino que lo llamaría específicicamente para esto del impostor.

2021-08-04 22:19 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/impostor/ImpostorActivity.kt
> +    }
de una

2021-08-04 22:22 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/impostor/ImpostorViewModel.kt
> +    }
okei, no le pongo nada

2021-08-04 22:23 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/impostor/create/CreateImpostorFragment.kt
> +        else resources.getString(R.string.lobby_no_players_yet)
hermoso

2021-08-04 22:28 UTC, brendaboryszanski commented on app/src/main/res/layout/fragment_create_impostor.xml
> +        app:layout_constraintTop_toTopOf="parent" />
deveno

2021-08-04 22:28 UTC, brendaboryszanski commented on app/src/main/res/layout/fragment_create_impostor.xml
> +        app:layout_constraintRight_toRightOf="parent"
deveno

2021-08-04 22:28 UTC, brendaboryszanski commented on app/src/main/res/layout/fragment_create_impostor.xml
> +        app:layout_constraintRight_toRightOf="parent" />
deveno

2021-08-04 22:29 UTC, brendaboryszanski commented on app/src/main/res/layout/fragment_create_impostor.xml
> +        android:layout_width="@dimen/text_field_size"
claro, sino quedaba enorme... okey lo pongo aca solo

2021-08-04 22:29 UTC, brendaboryszanski commented on app/src/main/res/layout/fragment_create_impostor.xml
> +        android:inputType="textVisiblePassword"
jjeje sorry

2021-08-04 22:29 UTC, brendaboryszanski commented on app/src/main/res/layout/fragment_create_impostor.xml
> +        app:layout_constraintRight_toRightOf="parent"
yeah

2021-08-04 22:29 UTC, brendaboryszanski commented on app/src/main/res/layout/fragment_create_impostor.xml
> +        app:layout_constraintRight_toRightOf="parent"/>
yeah

2021-08-04 22:54 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/clientlobby/ServerLobbyFragment.kt
> +class ServerLobbyFragment(override val gameViewModel: GameViewModel) : BaseGameFragment<
ahi hice eso

2021-08-04 22:54 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/clientlobby/ClientLobbyFragment.kt
> +        ClientLobbyViewModel,
lo cargo como una tarea asi llego a mergear esto para que arranquen el truco

2021-08-07 03:34 UTC, dylanmuszelml approved these changes

2021-08-07 03:34 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/impostor/ClientImpostorViewModel.kt
> +    fun assignWordAndStart(message: ImpostorAssignWord) = with(message){
```suggestion
    private fun assignWordAndStart(message: ImpostorAssignWord) = with(message){
```

2021-08-09 22:21 UTC, merged