Jugar impostor
UTN-FRBA-Mobile/Play2Play pull request #40
Opened 2021-07-13 23:55 UTC by brendaboryszanski

Se puede jugar al impostor! Falta centrar verticalmente la pantalla del cliente
  

https://user-images.githubusercontent.com/18487966/125539892-d446dd41-bf96-4381-bc95-6a0c53d25215.mp4

2021-07-17 01:11 UTC, dylanmuszelml requested changes
No entendí a qué te referís con "Falta centrar verticalmente la pantalla del cliente".

2021-07-17 01:11 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/impostor/ServerImpostorViewModel.kt
>  class ServerImpostorViewModel(
Hace falta tener esto si no va a hacer nada?

2021-07-17 01:11 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/impostor/play/PlayImpostorFragment.kt
> +            if (gameViewModel.isImpostor()) R.string.im_you_are_impostor else R.string.im_you_are_not_impostor
Acordate que no tenés nunca que preguntarle algo a viewmodel, siempre tenés que observarlo.

2021-07-17 01:11 UTC, dylanmuszelml commented on app/src/main/res/layout/fragment_play_impostor.xml
> +        app:layout_constraintTop_toTopOf="parent" />
Esto tiene que estar atado a los guidelines.

2021-07-17 01:11 UTC, dylanmuszelml commented on app/src/main/res/layout/fragment_play_impostor.xml
> +        app:layout_constraintRight_toRightOf="parent"
Same

2021-07-17 01:11 UTC, dylanmuszelml commented on app/src/main/res/layout/fragment_play_info_impostor.xml
> +        app:layout_constraintTop_toTopOf="parent" />
Saem

2021-07-17 01:11 UTC, dylanmuszelml commented on app/src/main/res/layout/fragment_play_info_impostor.xml
> +        app:layout_constraintRight_toRightOf="parent"
Same

2021-07-17 01:11 UTC, dylanmuszelml commented on app/src/main/res/layout/fragment_play_info_impostor.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Veo que te hiciste medio un quilombo acá, porque en vez de manejar las vistas con las constraints lo estás haciendo con padding muy a ojo y va a pasar que cuando el texto ocupe 2 lineas va a romper todo. Si querés para simplificar y porque no es necesario el constraint acá, podés usar un simple linear layout.

2021-08-04 21:55 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/impostor/ServerImpostorViewModel.kt
>  class ServerImpostorViewModel(
quedo mal, borrado

2021-08-04 22:05 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/impostor/play/PlayImpostorFragment.kt
> +            if (gameViewModel.isImpostor()) R.string.im_you_are_impostor else R.string.im_you_are_not_impostor
ahi lo puse en un liveData... pero poruqe era eso?

2021-08-04 22:07 UTC, brendaboryszanski commented on app/src/main/res/layout/fragment_play_impostor.xml
> +        app:layout_constraintTop_toTopOf="parent" />
se lo puse pero no se poruqe no me queda bien

2021-08-04 22:07 UTC, brendaboryszanski commented on app/src/main/res/layout/fragment_play_impostor.xml
> +        app:layout_constraintRight_toRightOf="parent"
![image](https://user-images.githubusercontent.com/18487966/128261618-810ccf0e-7d31-4fe1-9068-43af47e18d42.png)
idem no se poruqe no queda bien

2021-08-04 22:13 UTC, brendaboryszanski commented on app/src/main/res/layout/fragment_play_info_impostor.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
SIII!!!!!! PORUQE NO LO PENSE ANTESSSSS TAN SENCILLOOOOOOO VAMOS DYLAN VAMOS VAMOS DYLAN

2021-08-04 22:13 UTC, brendaboryszanski commented on app/src/main/res/layout/fragment_play_info_impostor.xml
> +        app:layout_constraintRight_toRightOf="parent"
VOLADO CONSTRAINTE

2021-08-04 22:13 UTC, brendaboryszanski commented on app/src/main/res/layout/fragment_play_info_impostor.xml
> +        app:layout_constraintTop_toTopOf="parent" />
VOLADO CONSTRAINTE

2021-08-04 22:13 UTC, brendaboryszanski commented on app/src/main/res/layout/fragment_play_impostor.xml
> +        app:layout_constraintRight_toRightOf="parent"
VOLADO CONSTRAINTE

2021-08-04 22:13 UTC, brendaboryszanski commented on app/src/main/res/layout/fragment_play_impostor.xml
> +        app:layout_constraintTop_toTopOf="parent" />
VOLADO CONSTRAINTE

2021-08-07 03:38 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/impostor/play/PlayImpostorFragment.kt
> +            if (gameViewModel.isImpostor()) R.string.im_you_are_impostor else R.string.im_you_are_not_impostor
La respuesta fea es porque así es el patrón de arquitectura MVVM, la vista observa cambios y notifica eventos al viewmodel. Pero acá eso es más importante porque los livedata manejan los ciclos de vida de Android, entonces te evitan muchos problemas de ir a buscar algo cuando por ejemplo no se cargó.

2021-08-09 17:51 UTC, dylanmuszelml requested changes

2021-08-09 17:51 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/impostor/play/PlayImpostorFragment.kt
> +                setScreenDescription(impostor)
Acá deberías u observar un objetito que contenga ambos valores u actualizar los textos en ambas acciones, porque si no estás dependiendo de cuál llegue primero.

2021-08-09 17:52 UTC, dylanmuszelml approved these changes
Cambiá esa boludez y estamos :)

2021-08-09 17:53 UTC, DylanMuszel approved these changes

2021-08-09 21:58 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/impostor/ServerImpostorViewModel.kt
>  class ServerImpostorViewModel(
jajaja juro que no esta

2021-08-09 22:20 UTC, merged