Seleccionar cantidad de rondas
UTN-FRBA-Mobile/Play2Play pull request #5
Opened 2021-05-22 21:23 UTC by florlipchak

Preview:

https://user-images.githubusercontent.com/31253446/119241135-aff4ab00-bb2a-11eb-8249-e3f775c4693b.mp4

2021-05-22 21:36 UTC, dylanmuszelml requested changes

2021-05-22 21:36 UTC, dylanmuszelml commented on app/build.gradle
> +    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
🤔 Esto no hace falta, ya se estaba usando constraint layout y ya se está importando más abajo. Por qué lo agregaste?

2021-05-22 21:36 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/home/games/GamesFragment.kt
> +        else -> Unit
No debería haber un `else`, todos los eventos deberían ser contemplados.

2021-05-22 21:36 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/home/games/gamesEvents.kt
> +object GoToTuttiFruttiLobby: GamesEvents()
Esto debería ser parte de un evento aparte, propio del view model.

2021-05-22 21:36 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/create/categories/CreateTuttiFruttiFragment.kt
> +        BaseFragment<FragmentCreateTuttiFruttiBinding, GamesEvents, CreateTuttiFruttiViewModel>() {
Esto no lo deberías haber borrado ni cambiado, por qué lo hiciste?

2021-05-22 21:36 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/create/categories/CreateTuttiFruttiFragment.kt
> +        else -> Unit
Lo mismo que arriba, no debería estar contemplado el else para obligar a que si se agrega un evento, se esté manejando.

2021-05-22 21:36 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/create/categories/CreateTuttiFruttiViewModel.kt
> +    BaseViewModel<GamesEvents>() {
Lo mismo que arriba 😅

2021-05-22 21:36 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/create/categories/CreateTuttiFruttiViewModel.kt
> +        dispatchSingleTimeEvent(GoToSelectRounds)
Me parece bien el cambio de nombre, eso sí.

2021-05-22 21:36 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/create/rounds/RoundsNumberFragment.kt
> +    BaseDialogFragment<FragmentRoundsNumberBinding, GamesEvents, RoundsNumberViewModel>() {
Acá debería tener su propio evento, RoundNumbersEvent o algo así.

2021-05-22 21:36 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/create/rounds/RoundsNumberFragment.kt
> +        binding.number.text = DEFAULT_ROUNDS_NUMBER.toString()
Esto debería ser parte del viewmodel. En el init le seteas a `_roundsNumber.value = DEFAULT_ROUNDS_NUMBER` y se va a actualizar solo.

2021-05-22 21:36 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/create/rounds/RoundsNumberFragment.kt
> +        binding.arrowLeft.setOnClickListener { viewModel.decrease(getNumber()) }
No debería hacer falta que se le esté pasando constantemente el número actual al viewmodel, ya el viewmodel debería tenerlo (de hecho ya lo tiene).

2021-05-22 21:36 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/create/rounds/RoundsNumberFragment.kt
> +        else -> Unit
Same, tengamos el TODO en el GoToTuttiFruttiLobby descomentado, no tengamos else.

2021-05-22 21:36 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/create/rounds/RoundsNumberViewModel.kt
> +            _roundsNumber.value = number + 1
```suggestion
        _roundsNumber.value = (number + 1).coerceAtMost(MAXIMUM_ROUND_NUMBER)
```

2021-05-22 21:36 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/create/rounds/RoundsNumberViewModel.kt
> +            _roundsNumber.value = number - 1
```suggestion
        _roundsNumber.value = (number - 1).coerceAtLeast(1)
```

2021-05-22 21:36 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/create/tuttiFruttiCategoriesEvents.kt
> -package com.p2p.presentation.tuttifrutti.create
Como dije arriba, no deberías borrar esto.

2021-05-22 21:36 UTC, dylanmuszelml commented on app/src/main/res/values/strings.xml
> +    <string name="tutti_frutti_rounds_number">1</string>
Borrá esto si no lo usás 😅

2021-05-22 23:07 UTC, florlipchak commented on app/build.gradle
> +    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
Jajajjja no lo agregué ah, supongo que habré tocado un alt + enter y se agregó.

2021-05-22 23:08 UTC, florlipchak commented on app/src/main/java/com/p2p/presentation/tuttifrutti/create/rounds/RoundsNumberViewModel.kt
> +            _roundsNumber.value = number + 1
guau

2021-05-22 23:16 UTC, florlipchak commented on app/src/main/java/com/p2p/presentation/tuttifrutti/create/rounds/RoundsNumberFragment.kt
> +        binding.arrowLeft.setOnClickListener { viewModel.decrease(getNumber()) }
uh, sí, había dicho lo hago así a ver si funciona y después pruebo sin pasárselo y colgué.

2021-05-23 17:02 UTC, dylanmuszelml requested changes

2021-05-23 17:02 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/create/categories/CreateTuttiFruttiFragment.kt
> +        GoToSelectRounds -> RoundsNumberFragment().show(childFragmentManager, "RoundsNumberDialog")
Acá hacele un método newInstance al fragment. En este caso es indistinto, pero se usa para que si hay que pasarle un parámetro (que se hace a través de bundle y no de constructores), lo haga el fragment y sea el fragment el que sepa cómo iniciarse. De nuevo, en este caso es indistinto, pero está bueno dejarlo así para mantener consistente el código y para tener la costumbre.

2021-05-23 17:15 UTC, dylanmuszelml commented
Y fijate de evitar usar margenes y cosas así para adecuar la pantalla, usá las constraints y/o paddings 😄

2021-05-24 14:34 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/base/BaseDialogFragment.kt
> +    @CallSuper
Sirve que para quienes lo implementen tengan que llamar a este super

2021-05-24 14:34 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/base/BaseDialogFragment.kt
> +abstract class BaseDialogFragment<VB : ViewBinding, E : Any, VM : BaseViewModel<E>> : DialogFragment() {
Me hace ruido que es semi igual a BaseFragment.. onda difiere de quien exitende...

No se puede hacer una interfaz unificando metodos?

2021-05-25 15:34 UTC, florencialipchak commented
Ahí actualicé a los colores de Vale y quedó así :)

![image](https://user-images.githubusercontent.com/35460863/119526100-7489f480-bd55-11eb-9569-0ce5fda38b65.png)

2021-05-25 15:35 UTC, florencialipchak commented on app/src/main/java/com/p2p/presentation/base/BaseDialogFragment.kt
> +abstract class BaseDialogFragment<VB : ViewBinding, E : Any, VM : BaseViewModel<E>> : DialogFragment() {
es que no, porque no es que DialogFragment y Fragment extienden de un mismo lado, en realidad es poco lo que se podría unificar, siento que complica más de lo que simplifica. Podríamos dejarlo para limpiarlo en otra tarea si no.

2021-05-25 16:10 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/base/BaseDialogFragment.kt
> +abstract class BaseDialogFragment<VB : ViewBinding, E : Any, VM : BaseViewModel<E>> : DialogFragment() {
genial

2021-05-25 16:12 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/tuttifrutti/create/categories/CreateTuttiFruttiFragment.kt
> +        GoToSelectRounds -> RoundsNumberFragment.newInstance().show(childFragmentManager, "RoundsNumberDialog")
Poruqe no lo llamas con el addFragment(RoundsNumberFragment.newInstance(), shouldAddToBackStack = true)
            ???

2021-05-25 23:36 UTC, DylanMuszel approved these changes

2021-05-25 23:36 UTC, DylanMuszel commented on app/src/main/res/layout/fragment_rounds_number.xml
> +        tools:ignore="ContentDescription" />
Jajajajaj esto técnicamente no lo deberíamos ignorar, es por accesibilidad. Si podés sacarlo y ponerle un contentDescription que explique para qué es el botón (onda "Decrease"), sería mejor 😅

2021-05-25 23:36 UTC, DylanMuszel commented on app/src/main/res/layout/fragment_rounds_number.xml
> +        tools:ignore="ContentDescription" />
Same

2021-05-25 23:36 UTC, DylanMuszel commented on app/src/main/res/values/dimens.xml
> +    <dimen name="small_extra">6dp</dimen>
No sirve small o medium? Técicamente material dice de usar dimens múltiplos de 4 en lo posible, pero si no ya fue.

2021-05-26 04:05 UTC, florencialipchak commented on app/src/main/res/values/dimens.xml
> +    <dimen name="small_extra">6dp</dimen>
ya fue, le pongo small

2021-05-26 04:06 UTC, florencialipchak commented on app/src/main/java/com/p2p/presentation/tuttifrutti/create/categories/CreateTuttiFruttiFragment.kt
> +        GoToSelectRounds -> RoundsNumberFragment.newInstance().show(childFragmentManager, "RoundsNumberDialog")
porque tengo que hacer el show! eso es propio del Dialog, no alcanza con solo crear el fragment.

2021-05-26 23:56 UTC, merged