Flujo de envido y truco
UTN-FRBA-Mobile/Play2Play pull request #55
Opened 2021-09-15 00:40 UTC by florlipchak

- Se agregan los flujos para cantar envido y truco
- Se agrega la acción "envido va primero" para cuando se quiere cantar truco en la primera ronda antes del envido
- Se valida que no se puedan cantar las acciones más de una vez
- Se envía por mensaje la acción realizada

Hecho con @brendaboryszanski 

https://user-images.githubusercontent.com/31253446/133351748-d04384ee-e28b-4bd3-8518-56119e6a2cca.mp4

https://user-images.githubusercontent.com/31253446/133351854-fa326ad3-b5f1-4133-a572-effe05a7d9c5.mp4

2021-09-15 04:04 UTC, vaalecav approved these changes
Re piola 🤗 dejo un par de comments

2021-09-15 04:04 UTC, vaalecav commented on app/src/main/java/com/p2p/presentation/truco/actions/TrucoActionsBottomSheetFragment.kt
> +        binding.trucoButton.alpha = if (enabled && !trucoDisabledForHand) 1f else 0.3f
Btw, con la modificación del alfa y eso, ya tenemos creados dos selectores para modificar el alfa del color del boton y del texto en base a si el mismo esta enabled o no. Estos son los archivos que digo por las dudas ` button_text_color.xml` y `button_primary_background_color.xml` / `button_secondary_background_color.xml`

2021-09-15 12:35 UTC, florlipchak commented on app/src/main/java/com/p2p/presentation/truco/ClientTrucoViewModel.kt
> +                startGame()
totalmente! Ahí lo saco.

2021-09-15 12:35 UTC, florlipchak commented on app/src/main/java/com/p2p/presentation/truco/TrucoPlayFor2Fragment.kt
> +            }
oh, sí, se hace solo cuando indento automáticamente, lo cambio.

2021-09-15 12:36 UTC, florlipchak commented on app/src/main/java/com/p2p/presentation/truco/TrucoViewModel.kt
> +            is Truco -> if (currentRound.requireValue() > 1) _trucoAlreadyAsked.value = true
Porque si no es la primera ronda y cantan truco, ya queda el truco como cantado. Ahora, si es la primera ronda puede pasar que vos cantes truco, yo te diga envido va primero, y después de eso vos cantes truco de nuevo, entonces no queremos deshabilitar el botón hasta no saber que efectivamente ya se cantó truco.

2021-09-15 12:37 UTC, florlipchak commented on app/src/main/java/com/p2p/presentation/truco/TrucoViewModel.kt
> +            is YesIDo, is NoIDont -> if (currentAction is Truco) _trucoAlreadyAsked.value = true
sip, es por la explicación de arriba, si es la primera ronda no va a entrar al primer if, entonces cuando me respondan sí o no al truco, ahí lo deshabilito.

2021-09-15 12:38 UTC, florlipchak commented on app/src/main/java/com/p2p/presentation/truco/actions/TrucoActionsBottomSheetFragment.kt
> +        binding.envidoOptionsButton.isEnabled = enabled && !envidoDisabledForHand
nop, porque el enabled se actualiza cada vez que se abre o colapsa el bottomSheet, para que no queden los botones clickeables entiendo, entonces hay que tener algo que lo mantenga deshabilitado durante toda la mano.

2021-09-15 12:38 UTC, florlipchak commented on app/src/main/java/com/p2p/presentation/truco/actions/TrucoActionsBottomSheetFragment.kt
> +        binding.trucoButton.alpha = if (enabled && !trucoDisabledForHand) 1f else 0.3f
ah no tengo ni idea de qué hace esto, lo dejé así porque estaba hecho por @DylanMuszel

2021-09-15 12:40 UTC, florlipchak commented on app/src/main/java/com/p2p/presentation/truco/actions/TrucoActionsBottomSheetFragment.kt
> +        observe(viewModel.currentRound) { if (it > 1) disableEnvidoForHand() } // Envido can only be asked on round 1
ah yo pensaba eso, no está hecho igual, pero lo asumí.

2021-09-15 14:03 UTC, dylanmuszelml requested changes

2021-09-15 14:03 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/truco/actions/TrucoActionsBottomSheetFragment.kt
> +        binding.trucoButton.isEnabled = (enabled && !trucoDisabledForHand)
Me parece que terminan dando muchas vueltas con esto por lo que ya existía y termina quedando complejo cuando es algo sencillo, yo volvería a lo anterior pero con un cambio

```suggestion
    private fun changeButtonsEnable(isEnvidoEnabled: Boolean, isTrucoEnabled: Boolean) {
        binding.envidoOptionsButton.isEnabled = isEnvidoEnabled
        binding.trucoButton.isEnabled = isTrucoEnabled```

2021-09-15 14:03 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/truco/actions/TrucoActionsBottomSheetFragment.kt
> +        disableEnvidoAndTrucoButtons()
Y esto mantenerlo como estaba
```suggestion
        changeVisibleButtonsEnable(false, false)
```

2021-09-15 14:03 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/truco/actions/TrucoActionsBottomSheetFragment.kt
> +        enableEnvidoAndTrucoButtons()
Y esto sería simplemente

```suggestion
        changeVisibleButtonsEnable(!envidoDisabledForHand, !trucoDisabledForHand)
```

2021-09-15 14:03 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/truco/actions/TrucoActionsBottomSheetFragment.kt
> +        binding.envidoOptionsButton.isEnabled = enabled && !envidoDisabledForHand
Y todo esto se iría

2021-09-15 14:03 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/truco/actions/TrucoActionsBottomSheetFragment.kt
> +        binding.trucoButton.alpha = if (enabled && !trucoDisabledForHand) 1f else 0.3f
Sí, creo que es porque había un bugcito visual que ya resolviste en otro PR val, si querés borralo ya flor

2021-09-15 14:04 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/truco/TrucoViewModel.kt
> +        currentAction = if (listOf(YesIDo, NoIDont).contains(action)) currentAction else action
Y, en todo caso, una boludez de sintaxis que me parece más bella, pero opinión personal nomás jejo
```suggestion
        currentAction = if (action in listOf(YesIDo, NoIDont)) currentAction else action
```

2021-09-15 22:12 UTC, vaalecav commented on app/src/main/java/com/p2p/presentation/truco/TrucoViewModel.kt
> +            is Truco -> if (currentRound.requireValue() > 1) _trucoAlreadyAsked.value = true
Aaaaaah barbaro!

2021-09-15 22:13 UTC, vaalecav commented on app/src/main/java/com/p2p/presentation/truco/actions/TrucoActionsBottomSheetFragment.kt
> +        observe(viewModel.currentRound) { if (it > 1) disableEnvidoForHand() } // Envido can only be asked on round 1
no es mala ah

2021-09-21 01:59 UTC, florlipchak commented on app/src/main/java/com/p2p/presentation/truco/actions/TrucoActionsBottomSheetFragment.kt
> +        enableEnvidoAndTrucoButtons()
no, cómo, la idea de poder deshabilitarlos para toda la mano es que justamente el onExpanded y onColapsed no me cambie esos valores, si no yo deshabilito el envido porque lo cantaron y en el onExpanded me lo va a poner en true. Para eso están el `envidoDisabledForHand` y el `trucoDisabledForHand`

2021-09-21 01:59 UTC, florlipchak commented on app/src/main/java/com/p2p/presentation/truco/actions/TrucoActionsBottomSheetFragment.kt
> +        binding.trucoButton.isEnabled = (enabled && !trucoDisabledForHand)
es que no, faltaría otro booleano para ver si está deshabilitado por toda la mano, no alcanza con el que se manda por el hecho de abrir o cerrar el bottomSheet

2021-09-21 02:03 UTC, florlipchak commented on app/src/main/java/com/p2p/presentation/truco/TrucoPlayFor2Fragment.kt
> +        gameViewModel.finishRound()
¿cómo? ¿Desde el viewModel llamar al Fragment? No entendí.

2021-09-21 02:04 UTC, florlipchak commented on app/src/main/java/com/p2p/presentation/truco/TrucoViewModel.kt
> +        currentAction = if (listOf(YesIDo, NoIDont).contains(action)) currentAction else action
Era para saber a qué acción me están contestando sí o no, y no pisarla justamente con el mensaje de sí o no. Igual ahora hay que rever esta lógica porque es cierto que falta el retruco y vale cuatro

2021-09-21 02:07 UTC, florlipchak commented on app/src/main/java/com/p2p/presentation/truco/actions/TrucoActionsBottomSheetFragment.kt
> +            }
no puede pasar eso, a menos que se pase a una nueva mano y ese es otro evento.

2021-09-21 02:08 UTC, florlipchak commented on app/src/main/java/com/p2p/presentation/truco/actions/TrucoAction.kt
> +        points = 30 - totalOpponentPoints
sip, es cierto. Hay que cambiarlo

2021-09-21 12:55 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/truco/TrucoPlayFor2Fragment.kt
> +        gameViewModel.finishRound()
Lo que digo es que el viewmodel debería en algún momento enviar un evento de finish round con estos datos, si no cómo llega el resultado de la ronda al fragment?

2021-09-21 12:58 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/truco/actions/TrucoActionsBottomSheetFragment.kt
> +        binding.trucoButton.isEnabled = (enabled && !trucoDisabledForHand)
Pero es que justamente, lo que se hace es guardarse esas variables y esto habilitarlo cuando corresponda 🤔

2021-09-21 12:58 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/truco/actions/TrucoActionsBottomSheetFragment.kt
> +        enableEnvidoAndTrucoButtons()
No entiendo, porque justamente es lo que se hace acá lo que vos decís

2021-09-23 01:28 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/truco/TrucoPlayFor2Fragment.kt
> +        gameViewModel.finishRound()
ah si!!! pero por eso el fragment tiene este todo,
![image](https://user-images.githubusercontent.com/18487966/134442538-6561d702-c1a2-42c8-b86f-7ef4678f7097.png)
osea cuando se llame se obtienen los valores que le mande el vm

2021-09-23 03:31 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/truco/TrucoViewModel.kt
> +            is YesIDo, is NoIDont -> if (currentAction is Truco) _trucoAlreadyAsked.value = true
done

2021-09-23 03:34 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/truco/actions/TrucoActionsBottomSheetFragment.kt
> +            }
saque el currentROund, pero los otros booleanos los deje

2021-09-23 04:52 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/model/base/message/Message.kt
> +    JsonSubTypes.Type(value = TrucoActionMessage::class),
Esto queda para poder crear la partida

2021-09-23 04:52 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/model/truco/message/TrucoActionMessage.kt
> +data class TrucoActionMessage(val action: TrucoAction) : Message(TYPE) {
Esto queda para poder crear la partida

2021-09-23 04:52 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/truco/ClientTrucoViewModel.kt
> +                goToPlay()
Esto queda para poder crear la partida

2021-09-23 04:52 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/truco/TrucoActivity.kt
> +        addFragment(CreateTrucoFragment.newInstance(), shouldAddToBackStack = false)
Esto queda para poder crear la partida

2021-09-23 04:52 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/truco/create/CreateTrucoFragment.kt
> +class CreateTrucoFragment : BaseGameFragment<
Esto queda para poder crear la partida

2021-09-23 04:52 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/truco/create/CreateTrucoViewModel.kt
> +class CreateTrucoViewModel : BaseViewModel<TrucoCreateEvents>() {
Esto queda para poder crear la partida

2021-09-23 04:52 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/truco/create/TrucoCreateEvents.kt
> +sealed class TrucoCreateEvents
Esto queda para poder crear la partida

2021-09-23 21:51 UTC, brendaboryszanski commented
@florlipchak falta lo de que solo se puede cantar envido va primero si es la ronda 1

2021-09-24 18:16 UTC, dylanmuszelml approved these changes
Dejé algunos comments, pero ni idea ah

2021-09-24 18:16 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/truco/TrucoViewModel.kt
> +    fun performTruco() {
Genial esto, pero no habría que cambiar el texto del "Truco" entonces?

2021-09-24 18:16 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/truco/TrucoViewModel.kt
> +    var currentActionPoints: Int = 0
No debería arrancar en 1?

2021-09-24 18:19 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/truco/TrucoViewModel.kt
> +    var currentActionPoints: Int = 0
todo esto en realidad no es de nuestra tarea... onda se va a tener que hacer bien dsp

2021-09-25 04:14 UTC, florlipchak commented
¡Fixeé la lógica para calcular los puntos!

2021-09-26 03:32 UTC, dylanmuszelml approved these changes

2021-09-26 03:32 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/truco/TrucoPlayFor2Fragment.kt
> -    private lateinit var theirCardsHand: TrucoCardsHand
Che, esto no se tiene que ir, qué onda? A lo sumo se puede cambiar para que no acepte las cartas del rival, pero está mal que se vaya porque sin esto nunca se muestran bien las cartas del rival. Igual ya lo agrego yo en otro PR, pero buen, lo aclaro por las dudas.

2021-09-26 03:37 UTC, dylanmuszelml requested changes

2021-09-26 03:37 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/truco/TrucoPlayFor2Fragment.kt
> +            actionResponseYesFaltaEnvido.setOnClickListener { gameViewModel.replyAction(gameViewModel.createFaltaEnvido()) }
Mmmmmmm esto no tiene sentido porque rompe con el patrón, perdón 😬 Debería llamarse a `gameViewModel.createEnvido(true)` (o algo así) que ya adentro llame al replyAction.

2021-09-26 03:37 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/truco/actions/TrucoAction.kt
> +        val alreadyReplicatedEnvido: Boolean,
La idea de esto era calcular los puntos, si no lo usas para eso, tiene sentido que siga estando?

2021-09-26 03:37 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/truco/actions/TrucoActionsBottomSheetFragment.kt
> +        envidoButton.setOnClickListener { viewModel.performAction(viewModel.createEnvido(false)) }
Same

2021-09-26 23:32 UTC, florlipchak commented on app/src/main/java/com/p2p/presentation/truco/actions/TrucoAction.kt
> +        val alreadyReplicatedEnvido: Boolean,
uh, sí, colgué con sacarlo

2021-09-26 23:32 UTC, florlipchak commented on app/src/main/java/com/p2p/presentation/truco/TrucoPlayFor2Fragment.kt
> -    private lateinit var theirCardsHand: TrucoCardsHand
ah, lo habíamos borrado porque habíamos hablado con vos y pensábamos que era de mock ah. Pero ya fue, queda en tu pr.

2021-09-27 02:29 UTC, dylanmuszelml approved these changes

2021-09-27 14:09 UTC, merged