Pantalla de puntajes finales del truco
UTN-FRBA-Mobile/Play2Play pull request #60
Opened 2021-09-27 21:21 UTC by vaalecav

## Descripción

- Se agrega la pantalla de puntajes finales del truco
- Los colores y textos varían según les ganadores/perdedores

## Screenshots

![photo_2021-09-27_18-17-05](https://user-images.githubusercontent.com/9021200/134986933-6bb8703c-7dc9-4491-95c7-acd458daadbc.jpg)
![photo_2021-09-27_18-17-05 (2)](https://user-images.githubusercontent.com/9021200/134986954-8618f1cf-6240-4cc3-aaba-a1507d31c5ef.jpg)

## Card Jira

https://play2play.atlassian.net/browse/P2P-124

2021-09-27 22:16 UTC, dylanmuszelml requested changes
Como siempre hermoso diseño 😭 Cualquier cosa preguntame!

2021-09-27 22:16 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/truco/TrucoViewModel.kt
> +    val finalScores: LiveData<List<TrucoFinalScore>> = _finalScores
Perdón por esto, pero en mi PR ya agregué los puntajes bien 😓 Está ourScore y theirScore, diría que o mergees mi PR o lo agregues acá.

2021-09-27 22:16 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/model/truco/message/FinalScoreMessage.kt
> +
Creeeeo entonces que esto no hace falta, simplemente en algún momento va a terminar y se va a llevar a esta página, no hace falta un mensaje que lo avise.

2021-09-27 22:16 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/truco/TrucoViewModel.kt
> +    }
Algo importante de MVVM es que la vista nunca puede llamar al viewmodel esperando una respuesta. O sea para hacer esto debería haber un livedata `isWinner`, por ejemplo, se entiende?

2021-09-27 22:16 UTC, dylanmuszelml commented on app/src/main/res/layout/fragment_truco_final_score.xml
> +        android:text="¡Ganamos!" />
Si esto está solo para poder verlo en la preview, entonces tiene que ir con `tools:text` en vez de `android:text`. Lo mismo en el resto.

2021-09-30 21:55 UTC, vaalecav commented on app/src/main/java/com/p2p/presentation/truco/TrucoViewModel.kt
> +    val finalScores: LiveData<List<TrucoFinalScore>> = _finalScores
De una ahora lo veo!

2021-09-30 23:46 UTC, vaalecav commented on app/src/main/java/com/p2p/presentation/truco/TrucoViewModel.kt
> +    }
Se entiende perfecto, gracias dyl! Igual ahora como ya se toman los puntajes nuevos que seteaste, esto fletaria 🤗

2021-09-30 23:47 UTC, vaalecav commented on app/src/main/res/layout/fragment_truco_final_score.xml
> +        android:text="¡Ganamos!" />
Hermoso! Siempre me peleo con lo mismo 😆

2021-09-30 23:48 UTC, vaalecav commented on app/src/main/res/layout/fragment_truco_final_score.xml
> +        android:text="¡Ganamos!" />
Hermoooooso! Siempre me peleo con lo mismo, gracias!

2021-10-01 00:44 UTC, vaalecav commented on app/src/main/java/com/p2p/model/truco/message/FinalScoreMessage.kt
> +
Claro, hermoso!

2021-10-03 20:19 UTC, florlipchak approved these changes
Llorando de lo hermoso

2021-10-04 21:09 UTC, dylanmuszelml approved these changes
Dejé una boludez más, solo como comentario y posible mejora. Si querés metelo, pero lo veo todo hermoso igualmente ♥️

2021-10-04 21:09 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/truco/finalscore/FinalScoreTrucoFragment.kt
> +            gameBinding.resultPoints.text = resources.getString(R.string.tr_points, resultOurScore)
Una boludez, pero no tiene sentido guardar en el fragment algo que ya tenemos en el viewmodel. Se podría resolver creando una clasesita en el final...viewmodel que sea `data class(val isWinner: Boolean, val ourScore: Int, val theirScore: Int)` y observar eso.

2021-10-05 00:15 UTC, merged