Tutti frutti game screen
UTN-FRBA-Mobile/Play2Play pull request #9
Opened 2021-05-25 19:54 UTC by brendaboryszanski

Pantalla de juego
Se hace la pantalla y se deja en un jira aparte toda la logica de la cantidad de rondas, puntos, etc.
Este jira va solamente enfocado a la creacion de la pantalla del juego con las categorias seleccionadas

![playGame](https://user-images.githubusercontent.com/18487966/119560008-c775a300-bd79-11eb-8d7d-a8ad7c534b94.gif)

2021-05-26 15:07 UTC, dylanmuszelml commented
Un detalle que me di cuenta después de la review, @vaalecav habría que ajustar el diseño?

2021-05-27 15:01 UTC, dylanmuszelml requested changes

2021-05-27 15:01 UTC, dylanmuszelml commented on app/src/main/res/layout/fragment_play_tutti_frutti.xml
> +        />
Algo importante que ayer quería marcar y hoy me acordé que me olvidé de hacerlo. Esto debería ser un solo TextView. `tf_letter` debería ser "Letra: %s" y para cargarlo se hay que hacer `resources.getString(R.string.tf_letter, letter)`.

2021-05-27 15:01 UTC, dylanmuszelml commented on app/src/main/res/layout/fragment_play_tutti_frutti.xml
> +        />
Lo mismo que arriba, `tf_round` sería `Ronda: %d/%d` y se carga como `resource.getString(R.string.tf_round, currentRound, totalRounds)`

2021-06-03 00:10 UTC, PadillaJuan approved these changes

2021-06-03 01:03 UTC, vaalecav approved these changes
Laburaso! Quedo hermoso 🤗

2021-06-03 01:03 UTC, vaalecav commented on app/src/main/res/values/categories.xml
> +        <item>Excusas para no ir al colegio</item>
<img src="https://media.giphy.com/media/l3M7smiKhkOcw/giphy.gif">

2021-06-03 01:03 UTC, vaalecav commented on app/src/main/res/values/strings.xml
> +    <string name="tf_validation_error">* Falta llenarlo!</string>
```suggestion
    <string name="tf_validation_error">* Falta completar!</string>
```

2021-06-03 01:39 UTC, dylanmuszelml requested changes
Algunas cosas:
- Habría que hacer la comunicación entre el server y los clientes, yo lo dejaría para otra tarea, pero va a implicar modificar muchas cosas que vos hiciste en el viewmodel.
- Tené cuidado en cómo se comunican el view model y el fragment: el fragment le dice cosas al viewmodel y observa sus cambios, nunca debería ir a pedir el valor de algo.
- Agregué una extension de livedata que es `requireValue()` para no tener que usar el doble signo de exclamación. Marqué algunos, pero no todos, revisá porfis los que faltan.

2021-06-03 01:39 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiViewModel.kt
> +    val actualLetter: LiveData<Char> = _actualLetter
No sería mejor reutilizar el RoundInfo que es una abstracción de estas dos cosas?

2021-06-03 01:39 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiViewModel.kt
> +        _actualLetter.value = lettersByRound[0]
Esto no es `generateNextRoundValues`? 
Más allá de eso, esto sería un mock? El valor real lo tiene que decidir el server y se lo tiene que comunicar al resto de los clientes.

2021-06-03 01:39 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiViewModel.kt
> +        availableLetters.map { it }.shuffled().subList(0, totalRounds.value!!)
Creo que se va a ir el `map` si hacés lo que vale dice abajo, pero si no es mejor el `.toList()`.
Además, usá `.take(totalRounds.requireValue())` que ya hace eso en vez de sublist.

2021-06-03 01:39 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiViewModel.kt
> +        }
Esta lógica no tendría que ser parte de la review? Y que desde la review el server mande el mensaje de startRound o algo así.

2021-06-03 01:39 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiViewModel.kt
> +        goToReview()
```suggestion
        goToReviewOrWait()
```
A la review solo va el server, los clientes tienen que esperar.

2021-06-03 01:39 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiViewModel.kt
> +        val actualRound: Int = actualRound.value!!
```suggestion
        val totalRounds: Int = totalRounds.requireValue()
        val actualRound: Int = actualRound.requireValue()
```

2021-06-03 01:39 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiViewModel.kt
> +        _actualRound.value = actualRound.value?.plus(1)
No, porque es nulleable

2021-06-03 01:39 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiViewModel.kt
> +        const val availableLetters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
A favor

2021-06-03 01:39 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/countdown/TuttiFruttiCountdownFragment.kt
> +                PlayTuttiFruttiFragment.newInstance() as Fragment)
Por qué lo casteas a Fragment? PlayTuttiFragment extiende de Fragment, ya es un fragment.

2021-06-03 01:39 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/countdown/TuttiFruttiCountdownFragment.kt
> +            addToBackStack(null)
No hay que agregarlo al backstack! Onda cuando vuelva para atrás (que ya hay una tarea en Jira para ver qué hacemos ahí) no tiene que aparecer la pantalla de countdown.

2021-06-03 01:39 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/create/categories/CreateTuttiFruttiViewModel.kt
> +        dispatchSingleTimeEvent(GoToSelectRounds(selectedCategories.value!!))
```suggestion
        dispatchSingleTimeEvent(GoToSelectRounds(selectedCategories.requireValue()))
```

2021-06-03 01:39 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/play/PlayTuttiFruttiFragment.kt
> +                    gameViewModel.selectedCategories.value!!.zip(values).toMap()
Nunca tenés que pedir desde el fragment el value al viewmodel. Lo mejor que se me ocurre así es que cuando crees los inputs guardes el mapa en el fragment, onda: `categoriesInputs: Map<Category, TextInputLayout>`.

2021-06-03 01:39 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/play/PlayTuttiFruttiFragment.kt
> +    private fun textViews(): List<TextInputLayout> {
```suggestion
    private fun getCategoriesTextInputs(): List<TextInputLayout> {
```
Para que se entienda qué está trayendo 😅 Igual si usás el mapa que te dije arriba esto volaría

2021-06-03 01:39 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/play/PlayTuttiFruttiFragment.kt
> +        gameViewModel.selectedCategories.value?.map { category ->
Me repito 😅 Nunca tenés que traer los values de un observer del viewmodel, pierde la gracia el observer si hacés esto jajaj. Observalo y actúa cuando cambie.

2021-06-03 01:39 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/play/PlayTuttiFruttiFragment.kt
> +        is EndRound -> {
```suggestion
        is FinishRound -> {
```

2021-06-03 01:39 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/play/PlayTuttiFruttiFragment.kt
> +        InvalidInputs -> markErrors()
```suggestion
        ShowInvalidInputs -> markErrors()
```

2021-06-03 01:39 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/play/PlayTuttiFruttiViewModel.kt
> +        else InvalidInputs
Si podés metele llves que si no cuesta leerlo porfis 🙏🏼

2021-06-03 01:39 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/utils/MapExtensions.kt
> +fun <T, N> MutableMap<T, N?>.nonNullable(): Map<T, N> = this.map { it.key to it.value!! }.toMap()
Esto se usa para algo? Si no yo lo borraría, porque es una util medio rara que si se tiene que usar es porque pasa algo raro jajaj

2021-06-03 01:39 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/tuttifrutti/play/PlayTuttiFruttiFragment.kt
> +        is EndRound -> {
![image](https://user-images.githubusercontent.com/65614580/120572427-4d38c480-c3f2-11eb-95a3-3bcd6e55b170.png)
😅

2021-06-03 01:39 UTC, dylanmuszelml commented on app/src/main/res/layout/fragment_play_tutti_frutti.xml
> +        android:textStyle="bold"
Yo sumé un style que ya tiene esto! Sacaselo y agregale: `style="@style/P2P_Title"`

2021-06-03 01:39 UTC, dylanmuszelml commented on app/src/main/res/layout/fragment_play_tutti_frutti.xml
> +        android:textStyle="bold"
Same

2021-06-03 01:39 UTC, dylanmuszelml commented on app/src/main/res/layout/play_category_item.xml
> +    app:layout_constraintTop_toTopOf="parent" >
Para qué el card view? No podrías poner directo el text input layout?

2021-06-03 01:39 UTC, dylanmuszelml commented on app/src/main/res/values/strings.xml
> +    <string name="tf_validation_error">* Falta llenarlo!</string>
Sumo al de vale jajaj
```suggestion
    <string name="tf_validation_error">¡Falta completar!</string>
```
Como opinión personal, le saqué el * porque eso se usa para poner en el label. Si estás tirando el error nunca vi que se ponga eso ahí.

2021-06-05 03:00 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiViewModel.kt
> +        const val availableLetters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
JAJAJAJA MANGA DE HDPS! PERO TE TOCA LA W Y NO PODES JUGAR!!

2021-06-05 03:01 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiViewModel.kt
> +        availableLetters.map { it }.shuffled().subList(0, totalRounds.value!!)
siipp

2021-06-05 03:02 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiViewModel.kt
> +        goToReview()
Nais!

2021-06-05 03:11 UTC, brendaboryszanski commented on app/src/main/res/layout/play_category_item.xml
> +    app:layout_constraintTop_toTopOf="parent" >
pense que no se podia!! ahi agregandole los primeros 3 atributos pude :)

2021-06-05 03:14 UTC, brendaboryszanski commented on app/src/main/res/layout/fragment_play_tutti_frutti.xml
> +        android:textStyle="bold"
ah hermoso

2021-06-05 03:15 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/utils/MapExtensions.kt
> +fun <T, N> MutableMap<T, N?>.nonNullable(): Map<T, N> = this.map { it.key to it.value!! }.toMap()
deleted

2021-06-05 03:22 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/tuttifrutti/create/rounds/RoundsNumberViewModel.kt
> +        dispatchSingleTimeEvent(GoToTuttiFruttiLobby(roundsNumber.value!!))
eliminado este metodo, no tiene sentido

2021-06-05 03:34 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiViewModel.kt
> +    val actualLetter: LiveData<Char> = _actualLetter
nice catch

2021-06-05 03:47 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/tuttifrutti/play/PlayTuttiFruttiViewModel.kt
> +        else InvalidInputs
obveo

2021-06-05 04:18 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/tuttifrutti/play/PlayTuttiFruttiFragment.kt
> +        gameViewModel.selectedCategories.value?.map { category ->
hermoso! ahi entendi

2021-06-05 04:18 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/tuttifrutti/play/PlayTuttiFruttiFragment.kt
> +        is EndRound -> {
hermoso

2021-06-05 04:22 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/tuttifrutti/countdown/TuttiFruttiCountdownFragment.kt
> +            addToBackStack(null)
aaaah okeiii

2021-06-05 04:22 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/tuttifrutti/countdown/TuttiFruttiCountdownFragment.kt
> +                PlayTuttiFruttiFragment.newInstance() as Fragment)
mala mia jeje

2021-06-05 04:25 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiViewModel.kt
> +        _actualLetter.value = lettersByRound[0]
cierto, le dejo un comment y creo jira para uqe cuando se cree se mande

2021-06-05 15:04 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiViewModel.kt
> +        _actualLetter.value = lettersByRound[0]
hermoso ahi modifique para que se haga en el generateNextRoundValues

2021-06-05 15:05 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiViewModel.kt
> +        availableLetters.map { it }.shuffled().subList(0, totalRounds.value!!)
No hare lo que dice vale, no voy a poner w jejej

2021-06-05 15:07 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiViewModel.kt
> +        }
totalmente, lo vuelo y que lo haga la parte de la review

2021-06-05 15:08 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/tuttifrutti/create/categories/CreateTuttiFruttiViewModel.kt
> +        dispatchSingleTimeEvent(GoToSelectRounds(selectedCategories.value!!))
done!

2021-06-05 15:10 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/tuttifrutti/play/PlayTuttiFruttiFragment.kt
> +                    gameViewModel.selectedCategories.value!!.zip(values).toMap()
me gustaria que se conozcan ambos viewmodels.. osea uqe extienda este del de tutti frutti, pero no puedo por los tipos. pero integremos esto y dsp me parece que estaria bueno un reafactor con eso

2021-06-05 15:20 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/tuttifrutti/play/PlayTuttiFruttiFragment.kt
> +    private fun textViews(): List<TextInputLayout> {
done, no volo poruqe se usa para los errores

2021-06-05 18:54 UTC, florlipchak commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiViewModel.kt
> +        availableLetters.map { it }.shuffled().toList().take(totalRounds.requireValue())
¿qué onda ese `.map { it }` ?

2021-06-05 19:04 UTC, florlipchak commented on app/src/main/java/com/p2p/presentation/tuttifrutti/play/PlayTuttiFruttiFragment.kt
> +    override val gameViewModel: TuttiFruttiViewModel by activityViewModels()
¿qué onda esto? ¿no tiene que construirse con una factory porque recibe parámetros?

2021-06-05 19:18 UTC, florlipchak commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiViewModel.kt
> +        availableLetters.map { it }.shuffled().toList().take(totalRounds.requireValue())
AH YA ENTENDÍ ERA PARA QUE QUEDE COMO LISTA? ahí sugiero cambio

2021-06-05 19:19 UTC, florlipchak commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiViewModel.kt
> +        availableLetters.map { it }.shuffled().toList().take(totalRounds.requireValue())
```suggestion
        availableLetters.toList().shuffled().take(totalRounds.requireValue())
```

2021-06-05 20:57 UTC, florlipchak commented on app/src/main/java/com/p2p/model/tuttifrutti/RoundInfo.kt
> +class FinishedRoundInfo(letter: Char, round: Int, val values: Map<Category, String>) :
¿qué onda el values? no se usa

2021-06-05 21:31 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/model/tuttifrutti/RoundInfo.kt
> +class FinishedRoundInfo(letter: Char, round: Int, val values: Map<Category, String>) :
Ahora no poruqe no se obtienen, pero cuando se termina una ronda se guarda una lista de rondas y los valores...
osea una ronda de FinishedRoundInfo, en las pantallas siguientes la agarras, y en la de resultados necesitas que se puso para cada categoria, podrias sino guardar solo los puntajes.. pero es a definir con las pantallas siguientes, pero iria aca sea puntaje o valores

2021-06-05 21:31 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/model/tuttifrutti/RoundInfo.kt
> +class FinishedRoundInfo(letter: Char, round: Int, val values: Map<Category, String>) :
Va... los valores son necesarios para la review, pero podria definirse si va en un actual_round values algo asi

2021-06-05 21:31 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/presentation/tuttifrutti/play/PlayTuttiFruttiFragment.kt
> +    override val gameViewModel: TuttiFruttiViewModel by activityViewModels()
estaba igual en todos los demas... no se poruqe no... @DylanMuszel ??

2021-06-05 21:35 UTC, florlipchak commented on app/src/main/java/com/p2p/presentation/tuttifrutti/play/PlayTuttiFruttiFragment.kt
> +    override val gameViewModel: TuttiFruttiViewModel by activityViewModels()
siiii, ahí dylan me dijo que es porque ya está creado el viewModel desde la activity y todos los fragments usan el mismo, lo saca de ahí.

2021-06-05 21:38 UTC, florlipchak commented on app/src/main/java/com/p2p/model/tuttifrutti/RoundInfo.kt
> +class FinishedRoundInfo(letter: Char, round: Int, val values: Map<Category, String>) :
aaaah, okay. O sea sería para cada pantalla de review, no? En ese caso esta info solo se guardaría en el server, y además de guardar los valores deberíamos saber de quién es cada valor, no? podríamos tenerlo en otro objeto aparte onda: 

```
class FinishedRoundInfo(letter: Char, round: Int, val valuesPerPlayer: List<PlayerValues>)

class PlayerValues(name: String, values: Map<Category, String>) 
```

2021-06-05 21:40 UTC, brendaboryszanski commented on app/src/main/java/com/p2p/model/tuttifrutti/RoundInfo.kt
> +class FinishedRoundInfo(letter: Char, round: Int, val values: Map<Category, String>) :
Sisisii, igual toda esta logica la dejaria para la pantalla de review...

2021-06-05 21:42 UTC, florlipchak commented on app/src/main/java/com/p2p/model/tuttifrutti/RoundInfo.kt
> +class FinishedRoundInfo(letter: Char, round: Int, val values: Map<Category, String>) :
siií, eso no tenés que hacerlo vos, pero ya que tenemos la clase lo dejaría así listo o al menos comentado y después otre lo hace.

2021-06-05 21:42 UTC, florlipchak approved these changes

2021-06-05 22:47 UTC, DylanMuszel approved these changes
Solo cambiá esas boludeces y está para mergear, gran laburo!
![](https://media3.giphy.com/media/rmi45iyhIPuRG/giphy.gif)

2021-06-05 22:47 UTC, DylanMuszel commented on app/src/main/java/com/p2p/presentation/tuttifrutti/TuttiFruttiViewModel.kt
> +open class TuttiFruttiViewModel(
Esto no tiene que ser open. Me imagino que lo hiciste por lo que hablamos, pero como te explique:
- El tuttifruttiviewmodel es un viemwodel que va a vivir durante todo el ciclo de vida de la activity, o sea durante todo el juego.
- El playtuttifruttiviewmodel es un viewmodel que tiene que solo tener la lógica específica de la pantalla, para no meter basura y que termine siendo este viewmodel enorme. 

Entonces nunca tendría que extenderse este viewmodel.

2021-06-05 22:47 UTC, DylanMuszel commented on app/src/main/java/com/p2p/model/tuttifrutti/RoundInfo.kt
> +class FinishedRoundInfo(letter: Char, round: Int, val values: Map<Category, String>) :
Claro, estoy de acuerdo, el problema con esto es que seguramente cambie, porque va a quedar mal porque no todos los viewmodels lo van a tener. Igual lo dejaría acá así y después lo cambio en la tarea que tengo yo que es esto, si te parece.

2021-06-05 22:47 UTC, DylanMuszel commented on app/src/main/java/com/p2p/presentation/tuttifrutti/create/rounds/RoundsNumberFragment.kt
> +//TODO change GameEvent for RoundsNumberEvent when lobby is done
Qué onda este TODO?

2021-06-05 22:47 UTC, DylanMuszel commented on app/src/main/java/com/p2p/presentation/tuttifrutti/play/PlayTuttiFruttiFragment.kt
> +    override val gameViewModel: TuttiFruttiViewModel by activityViewModels()
Exactoo, el activityViewModel es la misma instancia que se usa en la activity, por lo que no necesita el factory en los fragments porque nunca se va a instanciar desde acá

2021-06-05 22:47 UTC, DylanMuszel commented on app/src/main/java/com/p2p/presentation/tuttifrutti/play/PlayTuttiFruttiFragment.kt
> +        getCategoriesTextInputs().filter { it.text().isBlank() }.forEach {
Por qué no usas directamente `categoriesInputs.values()`?

2021-06-05 22:47 UTC, DylanMuszel commented on app/src/main/java/com/p2p/presentation/tuttifrutti/play/PlayTuttiFruttiFragment.kt
> +    //TODO validation inputs
Qué onda esto?

2021-06-05 22:47 UTC, DylanMuszel commented on app/src/main/java/com/p2p/presentation/tuttifrutti/play/PlayTuttiFruttiFragment.kt
> +        getCategoriesTextInputs().forEach { it.clear() }
Same

2021-06-06 18:25 UTC, vaalecav approved these changes
Genial bren , hermoso, faltarian los comments de dyl y atroden <3

2021-06-07 23:39 UTC, merged