Add hand icon for Truco
UTN-FRBA-Mobile/Play2Play pull request #91
Opened 2021-10-26 00:28 UTC by vaalecav

## Descripción

- Se agrega un ícono para señalar al jugador que es la mano

## Screenshots

TODO

## Jira Card
https://play2play.atlassian.net/browse/P2P-155

2021-10-30 18:52 UTC, vaalecav commented
El desarrollo de esto esta finalizado, pero no pude probarlo, pues es truco de 4 🤷

2021-10-31 19:15 UTC, dylanmuszelml requested changes
Dejo una boludez, capaz hoy a la noche lo pueda probar!

2021-10-31 19:15 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/truco/TrucoPlayFor4Fragment.kt
> +        }
```suggestion
        listOf(gameBinding.frontPlayerHand, gameBinding.leftPlayerHand, gameBinding.rightPlayerHand).forEach {
            is.isVisible = it == handPlayerIcon
        }
```
Y la lista en realidad la podrías tener declarada al principio como el resto de las cosas para simplificar 😅

2021-10-31 19:15 UTC, dylanmuszelml commented on app/src/main/res/layout/fragment_play_truco_for_4.xml
> +    <ImageView
Sé que no lo pudiste probar (yo todavía tampoco), pero siento que que esto esté antes o después de la palabra va a hacer que las palabras peguen saltos raris. Me parece que debería estar abajo/arriba o a lo sumo siempre del lado de adentro de la pantalla con respecto al texto.

2021-11-02 00:20 UTC, vaalecav commented on app/src/main/java/com/p2p/presentation/truco/TrucoPlayFor4Fragment.kt
> +        }
Hermoso!

2021-11-02 00:24 UTC, vaalecav commented on app/src/main/res/layout/fragment_play_truco_for_4.xml
> +    <ImageView
Te referis por si los nombres son muy largos / la pantalla muy chica no? 
Tiene sentido lo que decis jej pero no se donde agregarla si no. Osea si lo agrego arriba del nombre para todes, los jugadores de arriba tienen las cartas en esa posicion, y si lo agrego abajo bueno les de abajo lo mismo. 

Puedo ver de alternar, que para los de arriba la manito aparezca abajo del nombre y para los de abajo aparezca arriba. Te parece bien eso? 🤗

2021-11-02 00:38 UTC, vaalecav commented on app/src/main/res/layout/fragment_play_truco_for_4.xml
> +    <ImageView
Ahi lo deje asi, cualquier cosa lo ajusto!

2021-11-02 02:06 UTC, dylanmuszelml commented on app/src/main/res/layout/fragment_play_truco_for_4.xml
> +    <ImageView
Noo, me refería a que si está a un costado de la palabra y en algunos momento está y en otros no, el texto a veces iba a estar pegado a un costado y a veces no. Ahora quedó hermoso ♥️

2021-11-02 02:10 UTC, dylanmuszelml approved these changes
Encontré un super pequeño bugcito al probarlo porque la primera mano no se estaba mostrando nada. Lo corregí y quedó hermoso ♥️ Subo screens para que veas tu bello trabajo:
Cel. grande, mano|Cel. grande, no mano|Cel. mediano, no mano|Cel. chico, no mano
---|---|---|---
![image](https://user-images.githubusercontent.com/65614580/139775170-c8b58be5-38b7-4461-ac0f-e739ff06af3a.png)|![image](https://user-images.githubusercontent.com/65614580/139775274-61c5d791-de62-48ae-9d70-afa4411d30da.png)|![image](https://user-images.githubusercontent.com/65614580/139775204-5f383e87-0a0a-4d54-bc22-6b7dcaf27d0f.png)|![image](https://user-images.githubusercontent.com/65614580/139775310-adc5cf25-3d0e-4ac5-9ea0-2a8292a92c3c.png)

2021-11-02 03:08 UTC, vaalecav commented on app/src/main/res/layout/fragment_play_truco_for_4.xml
> +    <ImageView
Aaaaaa si tenes razon claro, como no lo vi no me di cuenta 😆

2021-11-02 03:09 UTC, vaalecav commented
> Encontré un super pequeño bugcito al probarlo porque la primera mano no se estaba mostrando nada. Lo corregí y quedó hermoso ♥️ Subo screens para que veas tu bello trabajo:
> 

Amo mil, gracias cosa por probarlo y por el feedback <3

2021-11-02 03:10 UTC, merged