Add truco ongoing points
UTN-FRBA-Mobile/Play2Play pull request #94
Opened 2021-10-30 20:21 UTC by vaalecav

## Descripción

- Se agrega label con puntos acumulados en el truco

## Screenshots

https://user-images.githubusercontent.com/9021200/139557394-f7baf7c8-6da4-4b90-871a-e246cbf49e71.mp4

## Jira card

https://play2play.atlassian.net/browse/P2P-156

2021-11-01 20:31 UTC, vaalecav commented
Se cambia el diseño, sugerido por @DylanMuszel 🤗

2021-11-02 00:46 UTC, dylanmuszelml requested changes
Perdóoooon por ser tan gede 😞

2021-11-02 00:46 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/truco/TrucoFragment.kt
> +        }
Perón, pero hay algo nativo que ya resuelve esto 😅 [Plurals / Quantity strings](https://developer.android.com/guide/topics/resources/string-resource#Plurals)

2021-11-02 00:46 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/truco/TrucoFragment.kt
> +        private const val POINTS_SINGULAR = "punto"
Con lo que te pasé arriba esto iría en el strings resources como corresponde

2021-11-02 00:46 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/truco/TrucoPlayFor4Fragment.kt
> +import com.p2p.utils.fromHtml
😓

2021-11-02 00:46 UTC, dylanmuszelml commented on app/src/main/java/com/p2p/presentation/truco/TrucoViewModel.kt
> +                updateTrucoAccumulatedPoints(lastAction, actionPoints)
Fijate que esto está quedando mal (aparece 4 en juego con retruco, 7 con vale cuatro, por ejemplo en el video). No hace falta usar otra variable, simplemente habría que hacer de currentActionPoints un livedata y listo, en mi opinión (aunque capaz el envido la cague con eso).

2021-11-02 03:11 UTC, vaalecav commented on app/src/main/java/com/p2p/presentation/truco/TrucoFragment.kt
> +        }
OOOOOh cheto! Gracias!

2021-11-02 03:20 UTC, vaalecav commented on app/src/main/java/com/p2p/presentation/truco/TrucoViewModel.kt
> +                updateTrucoAccumulatedPoints(lastAction, actionPoints)
Claro, el problema era que el truco no es la unica accion 🤔 Mala mia con lo de los puntos, asumi que estaban bien, tengo que chequear las reglas antes 😆 

Mañana chequeo en corregir esto, gracias!

2021-11-02 03:25 UTC, vaalecav commented on app/src/main/java/com/p2p/presentation/truco/TrucoViewModel.kt
> +                updateTrucoAccumulatedPoints(lastAction, actionPoints)
AAAAAH Porque lo estoy sumando! No estoy reemplazando la variable 🌚

2021-11-03 23:02 UTC, dylanmuszelml approved these changes

2021-11-03 23:20 UTC, merged